### PR TITLE
[TS] LPS-188827 | Metadata doesn't update after page publishing

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://liferay.atlassian.net/browse/LPS-188827
Best,
Attila

----
The root cause of the issue is that the layoutRevision head flag is only updated when the page is inspected. My solution forces a status update after every layout revision in the case of content pages.
The solution is based on https://liferay.atlassian.net/browse/PTR-4080

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
Hi @vendeltoreki, no regression issues were found.

cc @JoyceWang08211

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:stop

**Pull request closed without merging**
