### PR TITLE
LPS-143562 Removes file since it is not used

### PR DESCRIPTION
**Pull request by ealonso**
Hey @liferay-staging,

As part of https://issues.liferay.com/browse/LPS-140253, we've updated the export import and staging modules.

Regarding last two commits we've decided to removes the code instead of updating it, because for 7b65bb8 it is not used in any export import module and for b85a8a7 we don't have a PanelApp for export import, it is not used in any URL, include taglib or MVCRender class and it seems to be broken, see:

Export_Import_-_Liferay

Please let me know if you have any question.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
