### PR TITLE
LPS-166286 As a Site Template Administrator, I want the propagation process run in the background

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Review by vendeltoreki — COMMENTED** [review]
As discussed, I only discovered a typo in one of the commit messages: it should be LPS-166286 instead of LPS-166228 .
One more thing: we need a task ticket later for doing a cleanup. When the feature flag will be removed, a lot of code, including the propagation import background task will be unnecessary and can be deleted.
I ran some tests during debugging to check how parallel propagations behave and it seems like the current solution does not cause any issues.
So the code changes are ok from my side.

**Comment by moltam89** [comment]
I fixed the type and forced pushed my branch.
Also opened [LPS-181621](https://issues.liferay.com/browse/LPS-181621) for the cleanup.

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/283

**Pull request closed without merging**
