### PR TITLE
LPS-169003 Migrate Staging tree to new ClayTreeView component

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! 😄 I'm leaving this PR that migrates Staging tree view to new Clay component. Please tell me if you need any change, thanks!

Jira tickets
=======
Task: https://issues.liferay.com/browse/LPS-169001
Subtask: https://issues.liferay.com/browse/LPS-169003

Motivation
=======
The purpose of this task is migrating Staging tree to new ClayTreeView component. 

Additional information
========
- The new tree view is accesible and keyboard navigable. Use tab to move between tree items, space to check/uncheck items and left and right arrows to expand/collapse them
- In future subtasks, we will remove no needed code (https://issues.liferay.com/browse/LPS-169395) and feature flag (https://issues.liferay.com/browse/LPS-169004)
- We already passed tests in our repo (https://github.com/liferay-echo/liferay-portal/pull/10680) and our QAs think failures are not related to our changes

Steps to Verify
========
1. Enable feature flag: `feature.flag.LPS-169001=true`
2. There are five usages of this tree, this is the list and how to find them in portal:
- `export-import-web/export_layouts.jsp`: Publishing > Exports > + button
- `export-import-web/edit_publish_configuration.jsp`: Create a page > Navigate to view mode of the page  > Publish to Live > Switch to Advanced Publish Process
- `export-import-web/edit_export_configuration.jsp`: Publishing > Exports > Kebab menu > Export Templates > + button
- `staging-processes-web/publish_layouts.jsp`: Publishing > Staging > + button
- `staging-processes-web/edit_publish_configuration.jsp`: Publishing > Staging > Kebab menu > Publish Templates
4. Check the tree works as expected

Screenshots
========
image

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
No regression was found.
cc @vendeltoreki

**Comment by sandrodw3** [comment]
> No regression was found. cc @vendeltoreki

Hi @JoyceWang08211 @vendeltoreki! Does it mean we can try a forward? 😄 thanks!

**Comment by vendeltoreki** [comment]
Hi @sandrodw3 ,

I'm checking these changes locally now, just to make sure. I'm forwarding it as soon as it's done.

**Comment by sandrodw3** [comment]
> Hi @sandrodw3 ,
> 
> I'm checking these changes locally now, just to make sure. I'm forwarding it as soon as it's done.

That's cool! Thanks a lot @vendeltoreki

**Comment by vendeltoreki** [comment]
Forwarding manually: https://github.com/brianchandotcom/liferay-portal/pull/128172

**Pull request closed without merging**
