### PR TITLE
LPS-189191 -As a Site Administrator I want to be able to configure staging to ignore previews and thumbnails during publish process

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-189191](https://liferay.atlassian.net/browse/LPS-189191) - added the includeThumbnailsAndPreviewsDuringStaging checkbox, added new properties to language.properties, added DisplayContext to render_controls.jsp which includes the condition regarding the Thumbnails and previews

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
forwarding on https://github.com/liferay-staging/liferay-portal/pull/375

**Pull request closed without merging**
