### PR TITLE
[TS] LPS-192705 | Portlet preferences are getting lost during the propagation when using virtualhost other than the default one

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this?

https://liferay.atlassian.net/browse/LPS-192705
Best,
Attila

----

The root cause of the issue is that we store all shared preferences under plid = 0 and the localservice gets them all for plid = 0.
My solution is to simply filter the correct one from the result list based on companyID.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
No unique failures were found.
Testcases SitetemplatesUsecase#PortletPreferencesPersistWithSiteTemplateWhenSamePortletAddedOnSecondPage and NavigationMenusWithPreview#PreviewMenuInNavigationMenuEditor that failed on PR are passed on local.
cc @DaniSzimko

**Comment by DaniSzimko** [comment]
ci:test:stable

**Review by DaniSzimko — APPROVED** [review]
These changes look good to me. Thank you @bakayattila

**Comment by DaniSzimko** [comment]
ci:forward:force

**Pull request closed without merging**
