### PR TITLE
LPS-174417 Feature flags and site template warning bugfixes

### PR DESCRIPTION
**Pull request by vendeltoreki**
* Adding proper feature flag for epic [LPS-174417](https://liferay.atlassian.net/browse/LPS-174417)
* Fixing some impedibugs after https://github.com/brianchandotcom/liferay-portal/pull/137102 has been merged.

for [LPS-174431](https://liferay.atlassian.net/browse/LPS-174431):
[LPS-189307](https://liferay.atlassian.net/browse/LPS-189307) [Bug] Miss language key for confirmation dialog
[LPS-189315](https://liferay.atlassian.net/browse/LPS-189315) [Bug] No confirmation dialog appears when saving child page in site template with the collision

for [LPS-174434](https://liferay.atlassian.net/browse/LPS-174434):
[LPS-189319](https://liferay.atlassian.net/browse/LPS-189319) [Bug] Miss language key for confirmation dialog
[LPS-189321](https://liferay.atlassian.net/browse/LPS-189321) [Bug] No confirmation dialog appears when saving child page in site template with the collision

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 , @melodywu Please check the fixed issues by this PR, thank you!

**Comment by melodywu** [comment]
ci:test:bundle

**Review by JoyceWang08211 — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
Forwarding manually on https://github.com/brianchandotcom/liferay-portal/pull/137309 .

**Pull request closed without merging**
