### PR TITLE
LPS-143170 Moved Theme Setting radio option outside of choose block

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Hello,
Reviewed and looks good on my end. Let me know if there are any questions or comments, thanks!

https://issues.liferay.com/browse/LPS-143170

Quote from Jorge https://github.com/fortunatomaldonado/liferay-portal/pull/13
> I created a PTR ticket it was determined that this is an appropriate solution:
> https://issues.liferay.com/browse/PTR-2759

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @gaborlovasdotcom,

Can you please help to investigate whether the `Staging#StagingRemoteWithDynamicExportLimit` test failure is relevant in this case?

Thanks,
Vendel

**Comment by gaborlovasdotcom** [comment]
> Hi @gaborlovasdotcom,
> 
> Can you please help to investigate whether the `Staging#StagingRemoteWithDynamicExportLimit` test failure is relevant in this case?
> 
> Thanks, Vendel

Hi @vendeltoreki, the failed functional test case is not related to this PR, and has fix ticket already under [LPS-142697](https://issues.liferay.com/browse/LPS-142697)

**Comment by bakayattila** [comment]
ci:forward

**Pull request closed without merging**
