### PR TITLE
LPS-157420

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-157420](https://issues.liferay.com/browse/LPS-157420), Also see [LPS-162526](https://issues.liferay.com/browse/LPS-162526) which is the same issue.

We only want the "clearing" of the scopedPrimaryKeys to be temporary while we export the PortletPreferences. When we are finished, we need to restore them. Otherwise, we risk an infinite loop into a StackOverflowError later on down the line if there is a circular reference involving a Layout with a PortletPreferences, because every time the Layout is imported, the PortletPreferences will also be imported and clear the scopedPrimaryKeys. The scopedPrimaryKeys are how we prevent the infinite loop from occurring (see [this line](https://github.com/liferay/liferay-portal/blob/5329fcdb461f56b6921a56252983255a7ab0076c/portal-kernel/src/com/liferay/exportimport/kernel/lar/BaseStagedModelDataHandler.java#L83-L85), where we return early if we detect that the scopedPrimaryKey of the asset to be imported was already stored).

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
hi @mbowerman ,

I checked the code changes and they make sense. All the test failures seem to be irrelevant.
I will forward it as soon as possible.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by mbowerman** [comment]
@vendeltoreki Are we OK to manually forward this one since `ci:forward` seems to be failing right now?

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I'm forwarding this manually on https://github.com/brianchandotcom/liferay-portal/pull/123676

**Pull request closed without merging**
