### PR TITLE
LPS-149374 [Release] As an Instance Administrator, I want to be able to choose whether or not to publish content via display portlets

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
cc @gaborlovasdotcom , @weller0246

**Comment by weller0246** [comment]
ci:forward

**Comment by weller0246** [comment]
cI:stop

**Comment by weller0246** [comment]
ci:stop

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
Resent here with proper versioning:
https://github.com/liferay-staging/liferay-portal/pull/93

**Pull request closed without merging**
