### PR TITLE
LPS-190360 - As a Site Administrator I would like to see Staging recommendation before publishing

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190360](https://liferay.atlassian.net/browse/LPS-190360)

from https://github.com/liferay-staging/liferay-portal/pull/416

cc @vendeltoreki

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:sf

**Review by vendeltoreki — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
forwarded on https://github.com/liferay-staging/liferay-portal/pull/446

**Pull request closed without merging**
