### PR TITLE
LPS-190736 As a Site administrator I would like to be notified if the staging process may take some time

### PR DESCRIPTION
**Pull request by DaniSzimko**
Reverting [8d9adc4cc5510beb79c650017b6866755efb4cc8](https://github.com/brianchandotcom/liferay-portal/commit/8d9adc4cc5510beb79c650017b6866755efb4cc8) , based on this comment  : https://github.com/brianchandotcom/liferay-portal/pull/142884#issuecomment-1784972287

cc @laszlopap

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
All the related functional test cases passed on Jenkins.

**Comment by JoyceWang08211** [comment]
ci:forward

**Review by JoyceWang08211 — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
