### PR TITLE
LPS-141893 Extract method. Also, instead of using util, use service reference for FragmentEntryLocalService

### PR DESCRIPTION
**Pull request by jkappler**
Hi Team! Sending you also this PR since it touches export-import so that you can take a look. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
@ChrisKian, @ealonso

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @ChrisKian , @jkappler ,

Sorry for the delay in the review. It took me a while to completely understand the scenario. So basically, you want to publish the deletion of a fragment, but that can only be possible if all layouts that were using it are also published in the same go. Is that right?

My only concern was that when you publish a deletion of a `FragmentEntry`, you could basically 'cascade' that deletion to all related `FragmentEntryLink` records as well. However, in that case, the layouts still using the fragment in live would become inconsistent.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @ChrisKian ,

Thanks for the explanation. I think these changes will work quite well with local staging. However, I've found some issues while testing it with remote staging. The main problem is that on remote live, we don't have access to the layouts in remote staging during import. So when we try to get the staging `groupId` in https://github.com/liferay-staging/liferay-portal/pull/4/commits/e5f5252c0839707f4cc67f05cec052ec90e0b392#diff-eb5a32d920e349b77e6ece5a1d0acd7812e626119bed29afe606c894129d766bR104 , it will just return the same live group. Since `layoutId`s are generated from 1 for every site, it will randomly match layouts from the live group and base the deletions on that.
What I experienced is that it just throws a `RequiredFragmentEntryException()` (as one layout's draft and main layoutIds got mixed up) and did not delete any FragmentEntry or FragmentEntryLink records.
I would suggest sending layout UUIDs in the `extraData`, as they are the ones that will match across the live and staging groups in every scenario.

Can you please resend it with that change?

Thanks,
Vendel

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-staging/liferay-portal/pull/5

**Comment by vendeltoreki** [comment]
ci:close

**Pull request closed without merging**
