### PR TITLE
[TS] LPS-191924: retrieve updated Layout name from LayoutRevision to build correct path in breadcrumbs

### PR DESCRIPTION
**Pull request by jvelalr**
[LPS-191924](https://liferay.atlassian.net/browse/LPS-191924) - After a page name update, a "Link to Page" field in a web content structure, shows old page name while staging with page versioning is on

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @jvelalr ,

I'm checking this PR and the original change you submitted seems a bit suspicious to me, because it can possibly cause side-effects by setting a value in the `_layout`. I remember we had similar issues before, and we solved this by adding the method name to a list and implementing it in LayoutRevisionImpl. See example: https://github.com/brianchandotcom/liferay-portal/pull/81360/commits/d7d92f1f393327c1ce779f528b1c8a38dd7f0568 .
Do you think this a similar solution can be feasible in this case as well?

Thanks,
Vendel

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

@jvelalr is on PTO for some weeks, I will take care of this LPS.

I will send a new PR.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

I have implemented a new solution in PR https://github.com/liferay-staging/liferay-portal/pull/386 following your guidelines.

Thank you

**Pull request closed without merging**
