### PR TITLE
[TS] LPS-144446

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello team @liferay-staging, could you please review the change and confirm is safe? I'm not sure the tests failures are related...
thank you!

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

There's a `Bundle Version Change Recommended: 30.0.0` error, but I don't think your change https://github.com/liferay-staging/liferay-portal/pull/26/commits/e345f43a23cb959d1d19cdd167052c7fd1946722 caused it.
I'm restarting the tests to see if it's already fixed.

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by crodriguezy** [comment]
Ok @vendeltoreki , thank you.

I've started the staging tests with a dummy change here:  https://github.com/crodriguezy/liferay-portal/pull/245
And the same errors show up (except the version one)

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:forward

**Pull request closed without merging**
