### PR TITLE
[TS] LPS-172553 staging is available for sites with a name of a specific length

### PR DESCRIPTION
**Pull request by vendeltoreki**
Forwarding from: https://github.com/liferay-staging/liferay-portal/pull/229

cc: @GaborKomaromi

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
Reviewed test failures:
ci:test:staging:
- [PGStagingWithVersioning#AssertStagingVariationInfo](https://testray.liferay.com/home/-/testray/case_results/2189850866?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3Fstatuses%3D4%252C3%252C1%252C7%252C0%26testrayBuildId%3D2189850748%26testrayRunId%3D2189850776%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26status%3D4%252C3%252C1%252C7%252C0) waiting for a test fix LRQA-79358
- [com.liferay.staging.test.StagingDataPortletPreferencesTest](https://testray.liferay.com/home/-/testray/case_results/2189852012?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3Fstatuses%3D4%252C3%252C1%252C7%252C0%26testrayBuildId%3D2189850748%26testrayRunId%3D2189850776%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26status%3D4%252C3%252C1%252C7%252C0), flaky, test re-run probably pass it
- [LocalFile.Staging#StagingWithPublishTemplate](https://testray.liferay.com/home/-/testray/case_results/2189850916?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3Fstatuses%3D4%252C3%252C1%252C7%252C0%26testrayBuildId%3D2189850748%26testrayRunId%3D2189850776%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26status%3D4%252C3%252C1%252C7%252C0), flaky, test re-run probably pass it

I'm reevaluating ci:test:relevant results

cc @vendeltoreki

**Comment by gaborlovasdotcom** [comment]
ci:reevaluate:1367401_2990

**Comment by vendeltoreki** [comment]
Forwarding on: https://github.com/brianchandotcom/liferay-portal/pull/130075

**Pull request closed without merging**
