### PR TITLE
LPS-163289 High number of site template propagation lock attempts cause long response time

### PR DESCRIPTION
**Pull request by moltam89**
cc @gaborlovasdotcom

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant:norebase

**Comment by JoyceWang08211** [comment]
The following integration failures should be caused by the current changes:
1. com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutDeleteAndReadWithSameFriendlyURL
`[exec] com.liferay.exportimport.test.LayoutSetPrototypePropagationTest > testLayoutDeleteAndReadWithSameFriendlyURL FAILED
     [exec]     java.lang.AssertionError: expected:<4> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutDeleteAndReadWithSameFriendlyURL(LayoutSetPrototypePropagationTest.java:154)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)`
2. com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutPermissionPropagationWithLinkEnabled
`[exec] com.liferay.exportimport.test.LayoutSetPrototypePropagationTest > testLayoutPermissionPropagationWithLinkEnabled FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutPermissionPropagationWithLinkEnabled(LayoutSetPrototypePropagationTest.java:209)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)`
3. com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled
` [exec] com.liferay.exportimport.test.LayoutSetPrototypePropagationTest > testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled STARTED
     [exec] 
     [exec] com.liferay.exportimport.test.LayoutSetPrototypePropagationTest > testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled FAILED
     [exec]     java.lang.AssertionError: expected:<4> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled(LayoutSetPrototypePropagationTest.java:234)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)`

**Testray link:** https://testray.liferay.com/home/-/testray/case_results/1986352794
**Detailed Error log:** https://testray.liferay.com/reports/production/logs/2022-09/test-1-38/test-portal-acceptance-pullrequest(master)/3852/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

The above integration tests passed on the latest acceptance run: https://testray.liferay.com/home/-/testray/case_results/1989061757

**Comment by moltam89** [comment]
I could reproduce the test failures in my local environment, I'll need to investigate this.

**Pull request closed without merging**
