### PR TITLE
LRQA-79170 | master

### PR DESCRIPTION
**Pull request by JessieZhao0714**
https://issues.liferay.com/browse/LRQA-79170

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by JessieZhao0714** [comment]
ci:test:sf

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
