### PR TITLE
[TS] LPS-149307 | Links configured in page fragments within site templates don't work on sites when converted to public pages

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-149307
Best,
Attila

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 could you please evaluate the test results, and add additional tests if needed?

**Comment by moltam89** [comment]
I think this PR should be review by the Echo team.

**Comment by JoyceWang08211** [comment]
Hi @bakayattila Fragment belongs to echo team, I think it's better to send this PR to echo team.

BTW, the above functional failures are not related to this PR.

**Comment by bakayattila** [comment]
@JoyceWang08211 Thank you I will re-send the pull to the echo team.

**Pull request closed without merging**
