### PR TITLE
[TS] LPS-198081 and LPS-198082

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
[LPS-198081](https://liferay.atlassian.net/browse/LPS-198081)
[LPS-198082](https://liferay.atlassian.net/browse/LPS-198082)

**NOTE**, if the PR passes liferay-staging review please forward it to @liferay-echo

Motivation
=======
Importing of Master Page Templates where circular dependencies are present will result in the master page template being uneditable and the referencing page becoming private.

Proposed Solution
========
Master pages should not refer their draft pages in order to avoid importing the draft page before the published page and dirtying portletDataContext.isPrivateLayout. Let the published page handle this reference.

We should also retain the originally intended target LayoutSet as portletDataContext.isOriginalPrivateLayout so that all the switching of portletDataContext.isPrivateLayout would not affect other Layouts and their portlets other than the current Layout's scope.

Steps to Verify
========
The initial setup of both bugs is the same, but the issues are separable by affected models.
Please check https://liferay.atlassian.net/browse/LPS-198081 and https://liferay.atlassian.net/browse/LPS-198082

References to existing code
========
https://liferay.atlassian.net/browse/LPS-97509
https://liferay.atlassian.net/browse/LPS-156013
https://liferay.atlassian.net/browse/LPS-172534

Cheers,
Balázs

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:staging

**Review by vendeltoreki — APPROVED** [review]
I've checked whether there's viable a solution that does not add extra parameter to `PortletDataContext`. However, it seems like we can't avoid setting `privateLayout` in `PortletDataContext` during import, as the dependencies of pages use it.
 * `privateLayout` contains the information whether we are importing something in the context of a private or public page (can change during import process, e.g.: when we are processing page templates and their dependencies)
 * `originalPrivateLayout` this will contain the original intention, whether we are importing into a public/private LayoutSet, and we don't change this during the import process

cc: @balazssk

**Comment by vendeltoreki** [comment]
I tried to forward it to Echo team, but it seems like something's wrong with my GitHub as I can't create pull requests for some reason.

**Comment by JessieZhao0714** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
This change breaks the following integration tests:

1. com.liferay.layout.prototype.internal.exportimport.data.handler.test.LayoutPrototypeStagedModelDataHandlerTest > testImportCopyAsNew
```
[exec]     com.liferay.portal.kernel.exception.NoSuchLayoutException: {groupId=47780}
[beanshell]      [exec]     	at com.liferay.portal.model.impl.LayoutPrototypeImpl.getLayout(LayoutPrototypeImpl.java:49)
[beanshell]      [exec]     	at com.liferay.layout.prototype.internal.exportimport.data.handler.test.LayoutPrototypeStagedModelDataHandlerTest.testImportCopyAsNew(LayoutPrototypeStagedModelDataHandlerTest.java:128)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
``` 

2. com.liferay.layout.exportimport.service.test.ExportImportLocalServiceTest
```
[beanshell] 2023-10-16 01:49:41.030 ERROR [com.liferay.layout.test-executor-thread][LoggerExportImportLifecycleListener:390] Staged model {class: com.liferay.portal.kernel.model.Layout, groupId: 41565, uuid: 2a94e647-ab1f-aba3-fe02-58ce9b89f4c3} import failed
[beanshell] com.liferay.portal.kernel.exception.NoSuchLayoutException: {groupId=41626}
[beanshell] 	at com.liferay.portal.model.impl.LayoutPrototypeImpl.getLayout(LayoutPrototypeImpl.java:49) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.site.internal.util.SitesImpl.doMergeLayoutPrototypeLayout(SitesImpl.java:607) ~[?:?]
[beanshell] 	at com.liferay.site.internal.util.SitesImpl.mergeLayoutPrototypeLayout(SitesImpl.java:468) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutLocalServiceImpl._mergeLayout(LayoutLocalServiceImpl.java:4018) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.getLayout(LayoutLocalServiceImpl.java:1282) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor1644.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:862) ~[?:?]
[beanshell] 	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:701) ~[?:?]
[beanshell] 	at com.sun.proxy.$Proxy859.getLayout(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor1644.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy1106.getLayout(Unknown Source) ~[?:?]
``` 

cc @vendeltoreki and @balazssk

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @JessieZhao0714 
Not sure what is wrong, test builds are getting aborted. Are you aware of something that might be blocking them?

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Thanks @JessieZhao0714 and @balazssk for finding and fixing these test failures. The latest relevant runs don't seem to have related errors. I'm forwarding to Echo on https://github.com/liferay-echo/liferay-portal/pull/14068

**Pull request closed without merging**
