### PR TITLE
LPS-163289 Limit site template propagation attempts in one request thread

### PR DESCRIPTION
**Pull request by vendeltoreki**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
No regression was found. It's safe to forward.
cc @vendeltoreki and @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
> No regression was found. It's safe to forward. cc @vendeltoreki and @gaborlovasdotcom

Thanks @JoyceWang08211 , forwarding on https://github.com/brianchandotcom/liferay-portal/pull/128493

**Pull request closed without merging**
