### PR TITLE
LPS-157000 Removes unnecessary parameter

### PR DESCRIPTION
**Pull request by ealonso**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-157000)

Allow import custom fields on export/import.

## Proposed solution

Calculate the expando path using the classedModel, instead of using the path since it comes with a wrong groupId.

## Additional Notes

After some debugging I realized that the expando path is not correct, then when we try to get the expando values we always get null when we are importing a LAR between sites.

The paths in zip file are like this:

```
0 = "group/46483/com.liferay.bookmarks.model.BookmarksEntry/46671-expando.xml"
1 = "group/46483/com.liferay.bookmarks.model.BookmarksEntry/46671.xml"
2 = "group/46483/deletion-system-events.xml"
3 = "group/46483/links.xml"
4 = "group/46483/locks.xml"
5 = "group/46483/portlet/com_liferay_bookmarks_web_portlet_BookmarksAdminPortlet/1/portlet.xml"
6 = "group/46483/portlet/com_liferay_bookmarks_web_portlet_BookmarksAdminPortlet/46483/portlet-data.xml"
7 = "manifest.xml"
```

and in the case of expando we are looking for:

```
/group/46515/com.liferay.bookmarks.model.BookmarksEntry/46671-expando.xml
```

Note that the groupId is not the same, for that reason the file cannot be found.

## Steps to reproduce

1. Start Liferay
2. Log in and create a custom field for Site Navigation Menu Item, e.g. a text field "description"
3. Add a Navigation Menu, add a few pages, and add values for the new "description" field
4. Export the Navigation Menus into a LAR file and download it
5. Create a new site
6. Import the LAR file and inspect the menu items

Please let me know what do you think abut this approach.

Thanks!!

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
@vendeltoreki All 3 functional test cases are flaky, and waiting for tesfix in master.

**Comment by gaborlovasdotcom** [comment]
ci:reevaluate:1317401_6538

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
**Notes:** the "wrong" groupId is set here:
https://github.com/liferay/liferay-portal/blob/f3e6cb7e03b8052d24346daf12f80e86d86cf393/modules/apps/site-navigation/site-navigation-service/src/main/java/com/liferay/site/navigation/internal/exportimport/data/handler/SiteNavigationMenuStagedModelDataHandler.java#L73-L74

and here:
https://github.com/liferay/liferay-portal/blob/f3e6cb7e03b8052d24346daf12f80e86d86cf393/modules/apps/site-navigation/site-navigation-service/src/main/java/com/liferay/site/navigation/internal/exportimport/data/handler/SiteNavigationMenuItemStagedModelDataHandler.java#L160-L161

However, it makes sense and `StagedModelRepository.addStagedModel(..)` should not assume that the groupId of the stagedModel will always be the original one, that we got from the LAR file.

**Pull request closed without merging**
