### PR TITLE
[TS] LPS-189952 Always force propagation from site template to site when when updateLayoutSetPrototypeLinkEnabled

### PR DESCRIPTION
**Pull request by tototrinh**
Hi @vendeltoreki
Please help review this PR and leave your comments.
Ticket:
https://liferay.atlassian.net/browse/LPS-189952
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/138708
Root cause:
I found that when accessing the page, the mergeLayoutSetPrototypeLayouts process will be executed and acts as a background task. This is what causes the Home page not to exist when accessing the page for the first time.
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L1565-L1567
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L4056-L4062
Solution:
Always force propagation from site template to site when updateLayoutSetPrototypeLinkEnabled.
Thanks.

### CODE REVIEW

**Review by vendeltoreki — APPROVED** [review]
Tested the changes locally and it works as expected.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
No regression was found.

**Comment by JoyceWang08211** [comment]
The stable failure will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/138872. I will not forward the current PR until the fix is merged into master.

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
Hi @tototrinh, Could you please rebase the current PR to include this [change](https://github.com/shuyangzhou/liferay-portal/pull/11174/commits/e7c014fe1432f443f701aff527b7093b71a4e6e4)? Otherwise, the stable run will be failed.
Or you could send the PR to BChan directly since @vendeltoreki has approved this PR and no regression was found among these changes. Thx
cc @gaborlovasdotcom

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:stable

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
cc @DaniSzimko

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/394

**Pull request closed without merging**
