### PR TITLE
LPS-190064 - As a Site Administrator, I would like to see which web content was published in the summary, after a single asset publication

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190064](https://liferay.atlassian.net/browse/LPS-190064) - Clarify FeatureFlag title and description
@laszlopap

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:stop

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
As we agreed on retro today, I leave a comment here that this PR does not require QA. cc: @gaborlovasdotcom

**Comment by laszlopap** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
[Already merged] Directly sent to Brian here : https://github.com/brianchandotcom/liferay-portal/pull/142907

**Pull request closed without merging**
