### PR TITLE
[TS] LPS-198958 include pound char to stop reference

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,

Could you please review this pull request?
https://liferay.atlassian.net/browse/LPS-198958
Thank you!

----
**Reproduction Steps:**

1. Go to [Global site > Content & Data > Documents and Media > + > Multiple File Upload]

2. Drag the attached svg image

3. Export the documents and media to LAR file and download it

4. Go to [Global site > Design > Templates > Widget Templates > + > Site Map Template]

5. Set any name, add the following code and save

`<svg role="img" aria-label="左にスライド" width="24" height="24" viewBox="0 0 24 24"><use xlink:href="/documents/d/global/metrotokyo_icon#icon-metrotokyo-chevron-left-01"></use></svg>`

6. Optional: delete all default templates

7. Export the template to LAR file and download it

8. Shutdown liferay

9. Start a new clean bundle

10. Login as admin

11. Go to [Global site > Content & Data > Documents and Media] and imported the LAR file

12. Go to [Global site > Design > Templates > Widget Templates] and imported the LAR file

13, Edit the imported template
**Expected Result:** Imported data is the same as exported data
**Actual Result:** The URL has changed
`<use xlink:href="/documents/d/global/metrotokyo_icon">`

Solution:
Include pound character in the list of characters which stops the referencing.

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
cI:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
Code looks OK, waiting for CI results.

cc @GaborKomaromi

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
No regression was found.

cc @DaniSzimko and @GaborKomaromi

**Pull request closed without merging**
