### PR TITLE
LPS-161865 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-161865

### CODE REVIEW

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
@JoyceWang08211 Could you please include the lar reference file too?

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
I didn't see any unique failures caused by the current changes. I'll retrigger the relevant run.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
Sent to BChan under https://github.com/brianchandotcom/liferay-portal/pull/122570

**Pull request closed without merging**
