### PR TITLE
[TS] LPS-184372 - nosuchlayoutsetprototype exceptions can occur in remote staging due to missing verification | master

### PR DESCRIPTION
**Pull request by wanderlast**
Hi team!

This is being sent to Master branch since the code is present here, but cannot be tested due to [LPS-146160](https://issues.liferay.com/browse/LPS-146160). I've tested this fix primarily in 7.2, but in theory the code bases have seen virtually no changes and so they should work in the same manner.

This is a fix meant to help address a situation where due to a specific site template not being present on the 'live site' in a remote staging situation, pages are not accessible and a NoSuchLayoutSetPrototypeException occurs. While it's not the most graceful way to resolve the situation, the only way I could figure out how to handle it currently is to treat it in the same manner we do in import/export situations which is to actually verify if the template exists and toss the NoSuchLayoutSetPrototypeException *then*. While it won't fix currently existing sites with this error, it will address future cases. Please let me know if you have any suggestions or questions about this fix. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @wanderlast ,

Thanks for sending this pull request. Can you please check these points?
* Please rebase to latest master, [liferay-staging/liferay-portal](https://github.com/liferay-staging/liferay-portal/commits/master) repo seems to be in sync with [liferay/liferay-portal](https://github.com/liferay/liferay-portal/commits/master) now.
* Please check the [Pull request template](https://liferay.atlassian.net/wiki/spaces/ENGAPPSECURITY/pages/2289861613/Pull+request+template).
* Did you test this scenario with local staging as well? Does the export/import of site templates still work after the change?

Thanks,
Vendel

**Comment by wanderlast** [comment]
> Is this reproducible with Local Staging?

No, I'm assuming this is because the site template is still visible on the local instance. Export/Import still works as normal with this change in place from my testing since the only change was to remove the staging conditional on the verification step.

I've renamed the PR.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
@vendeltoreki The failing tests are not related to the changes in this PR

**Comment by vendeltoreki** [comment]
Hi @wanderlast ,

Thanks for rebasing the PR. Meanwhile, I ran some manual tests to try to understand the scenario completely. First I thought that when we are publishing remotely, we should completely detach the sites and pages from their templates, as it makes more sense. Also, from the `!group.isStaged()` condition it seemed like that was the original intention.
However, even if I just create a simple site template (with no global page templates involved) I still get the same `NoSuchLayoutPrototypeException` errors, and the remote live site crashes completely (not even showing the application menu).
So yes, it makes sense to validate for the site templates in remote live, and they should be there to successfully import.

I will forward the PR.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
