### PR TITLE
LPS-185081 Implementation of feature to allow whitelisting URL patterns during content validation

### PR DESCRIPTION
**Pull request by mbowerman**
Hello Staging team,

I am pre-emptively sending this implementation of the Story ticket [LPS-184978](https://issues.liferay.com/browse/LPS-184978). I checked all the listed Acceptance Criteria there and it passes all of them. I did change the verbiage of some things in ways that I thought were more clear and consistent with how similar messages were worded in Liferay.

I say "pre-emptively" because I have not yet hidden this feature behind a feature flag as requested. However, I wanted to get your review of it first. I was not sure how to hide the new configuration behind a Feature Flag, and I reached out in a private Slack channel for assistance with this. In fact, in my view, adding a Feature Flag for this almost feels redundant to me, because we are already adding a new Configuration for this, and the behavior will be the same as it was previously unless the new Configuration is modified. So in my mind, the new Configuration itself almost serves as a sort of "Feature Flag" already.

Story ticket [LPS-184978](https://issues.liferay.com/browse/LPS-184978)
Technical Task ticket: [LPS-185081](https://issues.liferay.com/browse/LPS-185081)

### CODE REVIEW

**Comment by mbowerman** [comment]
According to my discussions with other senior engineers, it seems that it is not possible to hide a specific configuration behind a feature flag. Entire configuration _screens_ can be hidden behind feature flags, but not individual configurations.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I'm not sure, but it's suspicious that some of the tests are failing because of the changes related to configuration.
See the jenkins log file: https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2768/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

It's possible that some kind of deadlock is happening:
```
     [java] 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
     [java] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
     [java] 	at com.liferay.portal.kernel.util.ServiceProxyFactory$AwaitServiceInvocationHandler.invoke(ServiceProxyFactory.java:252)
     [java] 	at com.sun.proxy.$Proxy341.getConfigurationBeanSettings(Unknown Source)
     [java] 	at com.liferay.portal.kernel.settings.SystemSettingsLocator.getSettings(SystemSettingsLocator.java:28)
     [java] 	at com.liferay.portal.kernel.settings.CompanyServiceSettingsLocator.getSettings(CompanyServiceSettingsLocator.java:43)
     [java] 	at com.liferay.portal.configuration.settings.internal.SettingsFactoryImpl.getSettings(SettingsFactoryImpl.java:91)
     [java] 	at com.liferay.portal.configuration.module.configuration.internal.ConfigurationProviderImpl.getConfiguration(ConfigurationProviderImpl.java:112)
     [java] 	at com.liferay.portal.configuration.module.configuration.internal.ConfigurationProviderImpl.getCompanyConfiguration(ConfigurationProviderImpl.java:96)
     [java] 	at com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.rebuildURLPatternMapper(ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.java:73)
     [java] 	at com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.lambda$rebuildURLPatternMappers$0(ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.java:100)
     [java] 	at com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl$$Lambda$1068/2060578025.accept(Unknown Source)
     [java] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:535)
     [java] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:516)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [java] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [java] 	at com.sun.proxy.$Proxy141.forEachCompanyId(Unknown Source)
     [java] 	at com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.rebuildURLPatternMappers(ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.java:97)
     [java] 	at com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.activate(ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl.java:123)
```
Can you please check?

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
Meanwhile, I checked the error message, and it seems like the DB upgrade process fails because it detects a circular dependency:
```
     [java] 2023-05-25 21:56:32.846 ERROR [main][ROOT:56] bundle org.apache.felix.scr:2.1.14.LIFERAY-PATCHED-7 (72)Circular reference detected trying to get service {com.liferay.exportimport.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelper}={component.id=2535, component.name=com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl, service.id=6201, service.scope=bundle, service.bundleid=608}
     [java]  stack of references: ServiceReference: {com.liferay.portal.configuration.persistence.listener.ConfigurationModelListener}={component.id=2536, component.name=com.liferay.exportimport.internal.configuration.persistence.listener.ExportImportServiceConfigurationModelListener, service.id=6202, service.scope=bundle, model.class.name=com.liferay.exportimport.configuration.ExportImportServiceConfiguration, service.bundleid=608}
     [java] ServiceReference: {com.liferay.exportimport.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelper}={component.id=2535, component.name=com.liferay.exportimport.internal.configuration.ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl, service.id=6201, service.scope=bundle, service.bundleid=608}
```

Most likely, `ExportImportServiceConfigurationModelListener` tries to update something while the configuration is not yet initialized.

**Comment by mbowerman** [comment]
Hello @vendeltoreki , I am so sorry that I missed your comment yesterday. I've pushed a [new commit](https://github.com/liferay-staging/liferay-portal/pull/313/commits/3771c5a1b5ab19420665b679576ef88a69660247) that seems to fix the issue in my testing. Could you please take a look and tell me if this is the right approach?

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:stable

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

Thanks for fixing the upgrade issue, it seems like that one is solved now.

However, as I see, `com.liferay.asset.link.exportimport.test.AssetLinkExportImportTest.testBothAssetEntriesExported` is failing:

https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/515109/testReport/com.liferay.asset.link.exportimport.test/AssetLinkExportImportTest/testBothAssetEntriesExported/

Stack-trace:
```
java.lang.NullPointerException
  at com.liferay.exportimport.internal.configuration.persistence.listener.ExportImportServiceConfigurationModelListener.onBeforeSave(ExportImportServiceConfigurationModelListener.java:78)
  at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager.lambda$store$5(ConfigurationPersistenceManager.java:277)
  at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:42)
  at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager._visitConfigurationModelListeners(ConfigurationPersistenceManager.java:613)
  at com.liferay.portal.configuration.persistence.internal.ConfigurationPersistenceManager.store(ConfigurationPersistenceManager.java:274)
  at org.apache.felix.cm.impl.persistence.PersistenceManagerProxy.store(PersistenceManagerProxy.java:203)
  at org.apache.felix.cm.impl.ConfigurationImpl.update(ConfigurationImpl.java:461)
...
```

Also, SemanticVersioning seems relevant:
```
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.exportimport.configuration             MINOR      2.1.0      2.1.0      2.2.0      VERSION INCREASE REQUIRED
```

I was checking the config and I think normally, we wouldn't need to override `onAfterSave(..)` method in https://github.com/liferay-staging/liferay-portal/pull/313/files#diff-28daf7f33394d874309f3796613bd76ef618a2f8451981362c2cd00da118a8a2R54 , as the `@Activate` of `ExportImportServiceConfigurationWhitelistedURLPatternsHelperImpl` should have been automatically triggered by every config change. However, this is not happening for some reason. I tested it by removing the `onAfterSave(..)` method, and it did not trigger the `@Activate`. It's only run when updating the config on the system level. So my guess is that `onAfterSave()` is required in this case.

Can you please look into these?

Thanks,
Vendel

**Comment by mbowerman** [comment]
Hi @vendeltoreki,

Thanks for catching those! I've force-pushed some changes that should fix them both. Since this pull request was getting messy, I closed it and opened a new one at https://github.com/liferay-staging/liferay-portal/pull/321.

**Pull request closed without merging**
