### PR TITLE
[TS] LPS-191924 After a page name update, a "Link to Page" field in a web content structure, shows old page name while staging with page versioning is on

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-191924

After a page name update, a "Link to Page" field in a web content structure, shows old page name while staging with page versioning is on, because the `getBreadcrumb` method retrieves the name from the Layout object instead of using the LayoutRevision one.

To solve it:

- 1d9efa34aa39a1b119c78e59c834e6d502af4b06 => I am adding a copy of the `getBreadcrumb` method of LayoutImpl in the LayoutRevision class
- 648c84672b02b008200051c79e5a5e1471727228 => Delegate the getAncestor to the Layout, to avoid repeating that code. Change the getName code to get it from the LayoutRevision of the different Layouts
- a440a9b11d5b6aa36fe66ce0a430b52fa722c201 => Add the `getBreadcrumb` to the _layoutRevisionMethodNames so the method call is redirected to the LayoutRevision object
- 6d758d2daa5b4cc039b2fc7a74cad35fad3b7610 and 46db02179ba7f2667e8bed050edf638392d9577b => Regen and Semver

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
cc @vendeltoreki

**Review by vendeltoreki — APPROVED** [review]
Looks good to me. Now the breadcrumb behaves consistently with the page's name.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
No regression was found.

**Comment by JoyceWang08211** [comment]
The stable failure will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/138872. I will not forward the current PR until the fix is merged into master.

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
Hi @jorgediaz-lr, Could you please rebase the current PR to include this [change](https://github.com/shuyangzhou/liferay-portal/pull/11174/commits/e7c014fe1432f443f701aff527b7093b71a4e6e4)? Otherwise, the stable run will be failed.
Or you could send the PR to BChan directly since @vendeltoreki has approved this PR and no regression was found among these changes. Thx
cc @gaborlovasdotcom

**Comment by jorgediaz-lr** [comment]
Hi @JoyceWang08211

I have rebased the PR

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:forward:force

**Comment by jorgediaz-lr** [comment]
Hi @JoyceWang08211

As you said here https://github.com/liferay-staging/liferay-portal/pull/386#issuecomment-1667093608 that you didn't found regressions, and the PR is approved by @vendeltoreki  I am going to manually forward this PR to Brian

**Comment by jorgediaz-lr** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/139013

**Pull request closed without merging**
