### PR TITLE
LPS-187023 - The error message is blocked by the title bar

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-187023](https://liferay.atlassian.net/browse/LPS-187023) - move error tags inside article-content-content div

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
