### PR TITLE
[TS] LPS-181432

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hello Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-181432
Thank you!

----

**Reproduction Steps:**
1. Navigate to Control Panel > Custom Fields > Document

2. Add a new custom field
    Field Type: Input Field
    Field Name: Text Field

3. Navigate to Control Panel > Custom Fields

4. Export the LAR file called "custom_fields.portlet.lar" that includes the custom field and download it

5. Add a virtual instance "www.able.com" and log in

6. Navigate to Control Panel > Custom Fields

7. Import the LAR file "custom_fields.portlet.lar"

8. Navigate to Control Panel > Custom Fields > Document

9. Assert the input field is present

10. Log out from www.able.com:8080 and log in to localhost:8080

11. Navigate to Control Panel > Custom Fields > Document

12. Delete the input field then export it called "custom_fields_deletion.portlet.lar" with Export Individual Deletions enabled

13. Log out from localhost:8080 and log in to www.able.com:8080

14. Navigate to Control Panel > Custom Fields

15. Import the LAR file "custom_fields_deletion.portlet.lar" with Replicate Individual Deletions enabled

16. Navigate to Control Panel > Custom Fields > Document

**Expected outcome:** The input field does not exist.
**Actual outcome:** The input field exists.

**Solution**
ExpandoColumns were not deleted if an import was made with individual deletions to other instances as the actual companyId is necessary, so I updated the method.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by zsigmondrab** [comment]
ci:forward:force

**Pull request closed without merging**
