### PR TITLE
LPS-190176 Integration Test

### PR DESCRIPTION
**Pull request by mbowerman**
Adding integration test as requested by Brian here: https://github.com/brianchandotcom/liferay-portal/pull/138258#issuecomment-1647805066

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Looking at the test failures, they don't seem to be caused by this change. I'm checking this with QA team.

**Comment by JoyceWang08211** [comment]
> ###  ci:test:stable - 28 out of 29 jobs passed
> ###  ci:test:relevant - 84 out of 89 jobs passed in 1 hour 37 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [f63af3907491f652f2c1eed4216b63825f26b1fc](https://github.com/liferay/liferay-portal/commit/f63af3907491f652f2c1eed4216b63825f26b1fc)
> 
> #### Upstream Comparison:
> Branch GIT ID: [81330886431d8c2f57de8dfe656b411d39e61340](https://github.com/liferay/liferay-portal/commit/81330886431d8c2f57de8dfe656b411d39e61340)Jenkins Build URL: [EE Development Acceptance (master) - 4718 - 2023-08-01[00:51:15]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397854523)
> 
> **ci:test:stable - 28 out of 29 jobs PASSED**
> #### 1 Failed Jobs:
> * build-iw-jdk8* [build-iw-jdk8/0/0](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/513663/)
> * central-requirements-jdk8* [central-requirements-jdk8/0/0](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660119/)
> * functional-smoke-tomcat90-mysql57-jdk8_stable* [functional-smoke-tomcat90-mysql57-jdk8_stable/0/0](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/644508/)
> * functional-upgrade-tomcat90-mysql57-jdk8_stable* [functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602266/)* [functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665777/)* [functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243214/)
> * js-unit-jdk8* [js-unit-jdk8/0/0](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262383/)
> * modules-compile-jdk8* [modules-compile-jdk8/0/0](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764080/)* [modules-compile-jdk8/0/1](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/665775/)* [modules-compile-jdk8/0/2](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/659371/)* [modules-compile-jdk8/0/3](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258248/)* [modules-compile-jdk8/0/4](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237359/)* [modules-compile-jdk8/0/5](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/246250/)* [modules-compile-jdk8/0/6](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/644507/)* [modules-compile-jdk8/0/7](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764082/)* [modules-compile-jdk8/0/8](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602265/)* [modules-compile-jdk8/0/9](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262382/)* [modules-compile-jdk8/0/10](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262381/)* [modules-compile-jdk8/0/11](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764081/)
> * modules-integration-mysql57-jdk8_stable* [modules-integration-mysql57-jdk8_stable/0/0](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373/)* [modules-integration-mysql57-jdk8_stable/0/1](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/660120/)* [modules-integration-mysql57-jdk8_stable/0/2](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764084/)
> * modules-unit-jdk8_stable* [modules-unit-jdk8_stable/0/0](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/587418/)
> * pmd-jdk8* [pmd-jdk8/0/0](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508372/)
> * portal-license-smoke-mysql57-jdk8* [portal-license-smoke-mysql57-jdk8/0/0](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508370/)
> * rest-builder-jdk8* [rest-builder-jdk8/0/0](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/198006/)
> * service-builder-jdk8* [service-builder-jdk8/0/0](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/513665/)
> * unit-jdk8_stable* [unit-jdk8_stable/0/0](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/736843/)
> * workspaces-compile-jdk8* [workspaces-compile-jdk8/0/0](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237356/)
> 
> **28 Successful Jobs:**
> **ci:test:relevant - 84 out of 89 jobs PASSED**
> ##### For more details click [here](https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8455/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-smoke-tomcat90-postgresql144-jdk8/0/0](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237355//consoleText)1. [com.liferay.portal.log.assertor.PortalLogAssertorTest](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237355/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest)1. [testScanXMLLog](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237355//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog)
> 2. [modules-integration-mysql57-jdk8_stable/0/0](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//consoleText)1. [com.liferay.change.tracking.rest.resource.v1_0.test.CTCollectionResourceTest](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373/testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTCollectionResourceTest) - [Failed 0 of last 21](https://testray.liferay.com/home/-/testray/case_results/2397861148/history)1. [testGraphQLDeleteCTCollection](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTCollectionResourceTest/testGraphQLDeleteCTCollection)2. [testGraphQLGetCTCollection](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTCollectionResourceTest/testGraphQLGetCTCollection)3. [testGraphQLGetCTCollectionNotFound](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTCollectionResourceTest/testGraphQLGetCTCollectionNotFound)2. [com.liferay.change.tracking.rest.resource.v1_0.test.CTProcessResourceTest](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373/testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTProcessResourceTest) - [Failed 0 of last 21](https://testray.liferay.com/home/-/testray/case_results/2397861155/history)1. [testGraphQLGetCTProcess](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTProcessResourceTest/testGraphQLGetCTProcess)2. [testGraphQLGetCTProcessNotFound](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTProcessResourceTest/testGraphQLGetCTProcessNotFound)3. [com.liferay.change.tracking.rest.resource.v1_0.test.CTEntryResourceTest](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373/testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTEntryResourceTest) - [Failed 0 of last 21](https://testray.liferay.com/home/-/testray/case_results/2397861150/history)1. [testGraphQLGetCTEntry](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTEntryResourceTest/testGraphQLGetCTEntry)2. [testGraphQLGetCTEntryNotFound](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/508373//testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTEntryResourceTest/testGraphQLGetCTEntryNotFound)
> 
> **Failures in common with [acceptance upstream results](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [8133088](https://github.com/liferay-staging/liferay-portal/commit/81330886431d8c2f57de8dfe656b411d39e61340):**

The failing integration tests were due to https://liferay.atlassian.net/browse/LPS-191729. No regression was found.
cc @vendeltoreki

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
