### PR TITLE
LPS-176242 Refuse exporting public pages while private export process

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-176242](https://issues.liferay.com/browse/LPS-176242)

If the referenced Layout in the EditableValuesLayoutMappingExportImportContentProcessor._exportLayoutReferences method is public, not a contentPageTemplate, not a masterPageTemplate, not assetTypeDisplay (those must be private in every case) and portletDataContext.isPrivateLayout == true (it means we are exporting private pages), then we should not export the layout, and we can avoid the Duplicate Entry error. This issue is blocked by [LPS-172531](https://issues.liferay.com/browse/LPS-172531),

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
I think we should forward this to the Echo Team.

**Review by vendeltoreki — APPROVED** [review]
Tested the changes, staging is activated successfully.

**Comment by DaniSzimko** [comment]
forwarding on : https://github.com/liferay-echo/liferay-portal/pull/13353

**Pull request closed without merging**
