### PR TITLE
LPS-187608 When saving a web content, the domain of links to documents and media are not correctly validated 

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-187608

**Note:** I originally sent this PR to echo team, see https://github.com/liferay-echo/liferay-portal/pull/12449 but @ealonso said this was not related to the Echo components.

When saving a web content, the domain of links to documents and media are not correctly validated:

The [DLReferencesExportImportContentProcessor._validateDLReferences](https://github.com/liferay/liferay-portal/blob/feac395f4b9015ad13cebe7af5fa58d9bd8586b0/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/exportimport/content/processor/DLReferencesExportImportContentProcessor.java#L784-L794) method is getting the hostname list from all existing instances (=company table), but it should get the virtualhosts from the current instance.

This causes some problems when you:

 - Link a image from other instance => Liferay is not able to get the DLFileEntry from the other instance, so it will consider it as a broken link
 - Link a image using a virtual host from a site of current instance => If you fill in a broken link, Liferay will consider it as a external link and it won't be validated as we are not using its domain.

To solve the issue, I am getting the instance hostnames from VirtualHost table instead of using the ones from Company_ table

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
@vendeltoreki These failures are not related to the changes in this PR.

**Review by vendeltoreki — APPROVED** [review]
I've checked the code and the changes look good to me. Thanks, @jorgediaz-lr !

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by jorgediaz-lr** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
