### PR TITLE
LPS-190015 - As a Site administrator I would like to manually select the web contents to publish

### PR DESCRIPTION
**Pull request by DaniSzimko**
Forwarding from: https://github.com/liferay-staging/liferay-portal/pull/433

cc @vendeltoreki

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by laszlopap** [comment]
ci:forward:force

**Pull request closed without merging**
