### PR TITLE
LPS-149979 Export process disappeared after upgraded from 7.0.10.16

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LPS-149979](https://issues.liferay.com/browse/LPS-149979)

with tests removed from quarantine

cc @moltam89, @JoyceWang08211

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
Upgrade tests are passing from 7.0.10.16, ready to forward @moltam89

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The failures of UIInfrastructureUsecase#... and RightToLeftInfrastructure#.. occur on the latest [acceptance run](https://testray.liferay.com/home/-/testray/case_results/1824572189), not related to current changes.

The failure of StagingUsecase#ActivateStagingForSiteWithTheme and StagingUsecase#PublishThemeFromStagedToLive are caused by [LPS-152675](https://issues.liferay.com/browse/LPS-152675). Based on the test report, the background color has already applied on home page.

Retrigger ci:test:relevant.

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
