### PR TITLE
LPS-122862

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-122862

/cc @javalosjr96

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I've looked at the failing test cases and 2 of them seems to be relevant:
* `LocalFile.CPSitetemplates#ViewJavaScriptPropagateviaSiteTemplate` the propagation of the Javascript field is not working. See reproduction steps in: [LRQA-68015](https://issues.liferay.com/browse/LRQA-68015)
* The new integration test `LayoutSetPrototypePropagationTest.testThemeSettingsWithLinkEnabled` is also failing, I could reproduce it locally as well.

I used master version 1ecb92a2247028da8bd0067cb8c66642e4e9c4f3 (rebased the pull commits on that one).

Can you please check these failing test cases?

Thanks,
Vendel

**Comment by mbowerman** [comment]
@javalosjr96 Can you please look into [Vendel's comments](https://github.com/liferay-staging/liferay-portal/pull/12#issuecomment-983467694)?

**Comment by javalosjr96** [comment]
@mbowerman Yes.

**Comment by javalosjr96** [comment]
@mbowerman 
LocalFile.CPSitetemplates#ViewJavaScriptPropagateviaSiteTemplate = Resolved

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
