### PR TITLE
[TS] LPS-150134 Prefer the scopeGroupId from the current layout instead of the live layout

### PR DESCRIPTION
**Pull request by jonathanmccann**
The previous logic would fetch the scope group ID from the live site, even if the user was viewing the staging site. This leads to issues because the widget's scope could potentially be different on staging than it is in live due to not being published yet. 

Additionally, this logic was not executed in the case of the live site because it failed the check `liveGroupLayout.hasScopeGroup()`. The scope could be a completely different layout or, in the case of staging, the scope group is the staged layout and not the live layout.

These changes use similar logic to `getPortletTitle` (https://github.com/liferay-staging/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L4577-L4580). If there is a scope group ID then it should be preferred. We then get the live group associated with that ID in order to fetch the correct data for the widget.

There are five cases that need to be considered for these changes:

1. Staging content page draft
2. Staging content page
3. Live content page
4. Staging widget page
5. Live widget page

I tested the content pages by:

1. Changing the scope of the staging content page draft and confirm it shows different content than the staging and live pages
2. Publish the page and confirm the staging page shows different content than the live page
3. Publish the page to live and confirm all three pages show the same content

I tested widget pages in the same way but omitting the draft portion. In all of these cases the code changes work as expected.

Since this is intricate logic and the code is rather old please let me know if you see any regressions or issues with the changes. If there are any questions please let me know as well.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @jonathanmccann ,

It seems like some scope-related tests are consistently failing for this change. E.g.: [ExportImportSiteWithAssetPublisherScopeSetting](https://github.com/liferay/liferay-portal/blob/a5474f1797ccc06b3f5f057916500fc6407c314c/portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/ExportImport.testcase#L1121).

@gaborlovasdotcom ,

Can you please help identify the failing tests?

Thanks,
Vendel

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1377401_1189

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:staging - 6 out of 13 jobs passed in 4 hours
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3060) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1377401_1189
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [a2265376ba9f4d89bfed81f20238c7ca88f3b6b4](https://github.com/liferay/liferay-portal/commit/a2265376ba9f4d89bfed81f20238c7ca88f3b6b4)
> 
> #### Upstream Comparison:
> Branch GIT ID: [563c772eb6d9e4383542834309d89899495cbe7a](https://github.com/liferay/liferay-portal/commit/563c772eb6d9e4383542834309d89899495cbe7a)Jenkins Build URL: [Acceptance Upstream DXP (master) #3059](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3059)
> 
> **ci:test:staging - 6 out of 13 jobs PASSED**
> ##### For more details click [here](https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1189/jenkins-report.html).
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478889/)###### Job Results:85 Tests Passed.1 Test Failed.1. [AXIS_VARIABLE=16 #478889](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=16/478889//consoleText)1. [LocalFile.ExportImport#ExportImportSiteWithAssetPublisherScopeSetting](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=16/478889//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExportImport_ExportImportSiteWithAssetPublisherScopeSetting_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/1/16/LocalFile.ExportImport_ExportImportSiteWithAssetPublisherScopeSetting/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/1/16/LocalFile.ExportImport_ExportImportSiteWithAssetPublisherScopeSetting/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/1/16/jenkins-console.txt.gz)
> 2. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/24552/)###### Job Results:90 Tests Passed.2 Tests Failed.1. [AXIS_VARIABLE=3 #24552](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/24552//consoleText)1. [LocalFile.PGStagingWithVersioning#AssertStagingVariationInfo](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/24552//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStagingWithVersioning_AssertStagingVariationInfo_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/LocalFile.PGStagingWithVersioning_AssertStagingVariationInfo/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/LocalFile.PGStagingWithVersioning_AssertStagingVariationInfo/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/jenkins-console.txt.gz)2. [LocalFile.PGStagingWithVersioning#AssertVariationInfoInPublishScreen](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/24552//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStagingWithVersioning_AssertVariationInfoInPublishScreen_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/LocalFile.PGStagingWithVersioning_AssertVariationInfoInPublishScreen/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/LocalFile.PGStagingWithVersioning_AssertVariationInfoInPublishScreen/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/2/3/jenkins-console.txt.gz)
> 3. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404918/)###### Job Results:61 Tests Passed.1 Test Failed.1. [AXIS_VARIABLE=3 #404918](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/404918//consoleText)1. [LocalFile.StagingUsecase#AssertDeletedAssetLinkRemovedFromLiveSite](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/404918//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecase_AssertDeletedAssetLinkRemovedFromLiveSite_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/3/3/LocalFile.StagingUsecase_AssertDeletedAssetLinkRemovedFromLiveSite/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/3/3/LocalFile.StagingUsecase_AssertDeletedAssetLinkRemovedFromLiveSite/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/3/3/jenkins-console.txt.gz)
> 4. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/485151/)###### Job Results:69 Tests Passed.4 Tests Failed.1. [AXIS_VARIABLE=19 #485151](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19/485151//consoleText)1. [LocalFile.StagingUsecase#StagingPublishChildSiteWithReference](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19/485151//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecase_StagingPublishChildSiteWithReference_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/19/LocalFile.StagingUsecase_StagingPublishChildSiteWithReference/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/19/LocalFile.StagingUsecase_StagingPublishChildSiteWithReference/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/19/jenkins-console.txt.gz)2. [AXIS_VARIABLE=21 #485151](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/485151//consoleText)1. [LocalFile.StagingUsecase#ViewPublishDMWithModifiedTitle](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/485151//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecase_ViewPublishDMWithModifiedTitle_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecase_ViewPublishDMWithModifiedTitle/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecase_ViewPublishDMWithModifiedTitle/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/jenkins-console.txt.gz)2. [LocalFile.StagingUsecaseWithRoles#StagingDemoLocalLive3](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/485151//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithRoles_StagingDemoLocalLive3_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecaseWithRoles_StagingDemoLocalLive3/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecaseWithRoles_StagingDemoLocalLive3/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/jenkins-console.txt.gz)3. [LocalFile.StagingUsecaseWithRoles#StagingDemoLocalLive4](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21/485151//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithRoles_StagingDemoLocalLive4_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecaseWithRoles_StagingDemoLocalLive4/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/LocalFile.StagingUsecaseWithRoles_StagingDemoLocalLive4/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/4/21/jenkins-console.txt.gz)
> 5. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/430132/)###### Job Results:47 Tests Passed.5 Tests Failed.1. [AXIS_VARIABLE=0 #430132](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/430132//consoleText)1. [LocalFile.StagingUsecaseWithVersioning#ChangeSitePageVariationInPagesAdmin](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/430132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_ChangeSitePageVariationInPagesAdmin_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithVersioning_ChangeSitePageVariationInPagesAdmin/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithVersioning_ChangeSitePageVariationInPagesAdmin/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/jenkins-console.txt.gz)2. [LocalFile.StagingUsecaseWithVersioning#DeleteChildPageFromVariationWhereNotEnabled](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/430132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_DeleteChildPageFromVariationWhereNotEnabled_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithVersioning_DeleteChildPageFromVariationWhereNotEnabled/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithVersioning_DeleteChildPageFromVariationWhereNotEnabled/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/0/jenkins-console.txt.gz)2. [AXIS_VARIABLE=1 #430132](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/430132//consoleText)1. [LocalFile.StagingUsecaseWithVersioning#EnableAndDeleteSitePageVariationPage](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/430132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_EnableAndDeleteSitePageVariationPage_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/1/LocalFile.StagingUsecaseWithVersioning_EnableAndDeleteSitePageVariationPage/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/1/LocalFile.StagingUsecaseWithVersioning_EnableAndDeleteSitePageVariationPage/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/1/jenkins-console.txt.gz)3. [AXIS_VARIABLE=2 #430132](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/430132//consoleText)1. [LocalFile.StagingUsecaseWithVersioning#StagingMergeSitePagesVariation1](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/430132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_StagingMergeSitePagesVariation1_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingMergeSitePagesVariation1/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingMergeSitePagesVariation1/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/jenkins-console.txt.gz)2. [LocalFile.StagingUsecaseWithVersioning#StagingMergeSitePagesVariation2](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/430132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_StagingMergeSitePagesVariation2_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingMergeSitePagesVariation2/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingMergeSitePagesVariation2/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/1189/functional-tomcat90-mysql57-jdk8/5/2/jenkins-console.txt.gz)
> 6. ...

All the above functional failures are not related to the current PR, they are also failed on the latest ci:test:upstream-dxp run. Please see details in this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1645465149&testrayRunIdA=1645928025&testrayTeamId=1310723283&statusB=3).

cc @gaborlovasdotcom and @vendeltoreki

**Comment by JoyceWang08211** [comment]
The above functional failure PortalSmokeUpgrade#ViewPortalSmokeArchive70106 is not related to the current PR.

**Comment by jonathanmccann** [comment]
That is correct in the case of Content Pages.

- Draft layout shows the correct content since it steps into the current `hasScopeGroup` check
- Published staging page does not show the correct content
- Published live page does not show the correct content

I agree that `hasScopeGroup` check doesn't seem to work well with Content Pages or staging since only a single page will have the scope group.

The client is under a deadline so if your preliminary analysis deems it safe for an SDH please let me know. Then we can spend more time testing and adding tests for this use case.

**Comment by moltam89** [comment]
I'm not sure what should happen when the layout hasn't been published to Live yet and there is a page scoped portlet on it.

Before the fix, the Live Site's groupId was used.
After the fix, we keep the layout's scope, which is a staged group where we shouldn't add content when the portlet is not staged.

I don't really like any of these options, maybe we would need a warning or remove the add new entry button and only let users create content, when the live layout/group is ready.

Except this use case, the fix looks good to me, it should be okay to deliver this as an SDH, we should just let the customer know that the behaviour for this corner case might change in the future.

**Comment by jonathanmccann** [comment]
I tested the steps on https://issues.liferay.com/browse/LPS-150134 but enabled local live staging first so that none of the pages were live yet. Everything still worked as expected. I agree that it is strange though to be referencing a staging draft layout's scope but I fear changing how this works would be a massive overhaul.

I'll go ahead and deliver this as an SDH so take your time with this review so that we make the right changes.

**Comment by moltam89** [comment]
Before we merge this fix, I'd like to create tests.
We'll need to prioritise this with the Staging team, I think we should be able to add this to our next sprint, or the one after that and finish it in 2-4 weeks.

Let me know if this is feasible for you, I'll talk to the Staging team in the meantime.

**Comment by jonathanmccann** [comment]
That is fine with me. I've been trying to make time to look at the tests but we're overwhelmed at the moment unfortunately. Please let me know if there's anything else you need from me and I'll let you know if I have time to circle back around to making the tests.

**Comment by moltam89** [comment]
Okay, we created [LPS-151010](https://issues.liferay.com/browse/LPS-151010) for the tests.

I'll get back to you once I start working on it, probably in our next sprint, starting on the 18th of April.

**Comment by moltam89** [comment]
I'm closing this PR, because the fix is not aligned to the tests.

Let me know if the tests should be updated instead.

Best,
Tamas

**Pull request closed without merging**
