### PR TITLE
LPS-151464 Check if the page exists with the urlWithoutLocale in more cases (not only if the URL only has 1 slash)

### PR DESCRIPTION
**Pull request by robertoDiaz**
Sending this because the urls with locale and more than 1 slash (for example /en/test/test are not passing the validation because the locale is not been removed when needed.

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @liferay-staging 

Any update? A customer is waiting for this fix.

**Comment by vendeltoreki** [comment]
Hi @robertoDiaz ,

Sorry for the delay. The test failures seem to be irrelevant to this case, as they were failing with the same errors without this change.
I'm still running some manual tests to see whether this change can cause any regressions.

Regards,
Vendel

**Comment by robertoDiaz** [comment]
Thank you for the update @vendeltoreki!

**Comment by vendeltoreki** [comment]
Forwarding to: https://github.com/liferay-echo/liferay-portal/pull/7828

**Pull request closed without merging**
