### PR TITLE
LRQA-78538 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-78538

### CODE REVIEW

**Comment by weller0246** [comment]
Test passed on self [PR](https://github.com/liferay-staging/liferay-portal/pull/189)

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
LGTM.

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
