### PR TITLE
[TS] LPS-191484

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR aims to fix an undesired effect revealed by LPS-168616. After normalizing the attribute itemsTotal to disable the checkbox when this value is 0, the checkbox Select All is permanently disabled.

Since it would need a considerable refactoring of the module to properly establish this value, the chosen approach is to inform this value through the related PropsTransformer.

Could you please review it?

Thanks in advance!

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
No regression was found. The stable run failed due to [LPS-197234](https://liferay.atlassian.net/browse/LPS-197234), PortalSmoke#Smoke failed due to [LPS-196932](https://liferay.atlassian.net/browse/LPS-196932).

cc @DaniSzimko and @dacousalr

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
Code looks OK, thank you @dacousalr

**Comment by DaniSzimko** [comment]
ci:forward:force

**Pull request closed without merging**
