### PR TITLE
LPS-190064 - As a Site Administrator, I would like to see which web content was published in the summary, after a single asset publication

### PR DESCRIPTION
**Pull request by DaniSzimko**
Forwarding from https://github.com/liferay-staging/liferay-portal/pull/409

cc @vendeltoreki

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by laszlopap** [comment]
ci:forward:force

**Pull request closed without merging**
