### PR TITLE
LPS-163142 Fix possible NullPointerException

### PR DESCRIPTION
**Pull request by mbowerman**
See [LPS-163142](https://issues.liferay.com/browse/LPS-163142) for details

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
@vendeltoreki relevant tests are not connected to the contents of the PR.

**Comment by mbowerman** [comment]
Hey @vendeltoreki ,

I noticed that when testing [LocalFile.ExportImport#ImportStagedSiteWithCircularReference](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/104248//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExportImport_ImportStagedSiteWithCircularReference_) in master (without my changes), the NullPointerException reported in [LPS-163142](https://issues.liferay.com/browse/LPS-163142) occurs, but the publish succeeds anyway.

I guess the act of changing the NullPointerException to a PortletDataException causes the publish to fail when the exception is thrown? Whereas when it's a NullPointerException, the publish is still allowed to succeed?

If that's the case, then I guess I can just get rid of the "Better error reporting" and subsequent commits. What do you think about that?

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

Yes, the `PortletDataException` can be the issue. I remember, we used a fallback for importing some circular references. The first attempt failed (intentionally), so the second one could import the asset properly. I'm not sure whether this is the one though.
Found the source of test case of [ImportStagedSiteWithCircularReference](https://github.com/liferay/liferay-portal/blob/d1d7e6db020143fcca0c6bb314dd937b9ad9368f/portal-web/test/functional/com/liferay/portalweb/tests/enduser/exportimport/ExportImport.testcase#L2363). According to this, it's describing the cases of [LPS-97544](https://issues.liferay.com/browse/LPS-97544) and [LPS-90886](https://issues.liferay.com/browse/LPS-90886). The error happens at the import phase of the publish process.
I will test this locally as well. It seems reasonable, that a NullPointerException should fail the import process. Although, it might be necessary in some edge cases to ignore it and import again later in the same process.

**Pull request closed without merging**
