### PR TITLE
LPS-144446 Integration test

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello team, here the integration test added for LPS-144446

**Comment by crodriguezy** [comment]
hi @liferay-staging, were you able to review this PR?
Thanks

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

I'm reviewing this integration test now.
Unfortunately, we noticed too late that the original fix ( https://github.com/liferay-staging/liferay-portal/pull/26 ) caused an issue, so it has been reverted and changed on https://github.com/liferay-staging/liferay-portal/pull/29 .
However, as I see, the test you submitted now should still work, as it tests the whole export-import process.
Sorry for the confusion, we were not sure at first, how the page tree selection should really work. After some discussions with the staging product team we will document it properly. It's also likely that we will make some fixes on the front-end as well.

Thanks,
Vendel

**Comment by crodriguezy** [comment]
I see @vendeltoreki . thanks for the info. However I'm not sure the test will work after reverting my changes.

Will you please update https://issues.liferay.com/browse/LPS-144446 when you have the updated documentation and add a link to the related front-end fixes? The customer who found this "bug" made a complaint on how confusing was the interface, and they already have the fix...

**Comment by crodriguezy** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Forwarding through https://github.com/liferay-staging/liferay-portal/pull/32

**Pull request closed without merging**
