### PR TITLE
LPS-145357

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-145357

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

The changes look ok to me, but the CI keeps failing for some reason. I assume the errors are not related to this fix.
I will try to run them again tomorrow.

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Forwarding to: https://github.com/liferay-lima/liferay-portal/pull/2666

**Pull request closed without merging**
