### PR TITLE
LPS-166515 As a Site Admistrator, I want the LAR files used for Site Template propagation to be removed from the Document and Media library

### PR DESCRIPTION
**Pull request by hhtank**

### CODE REVIEW

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:sf
ci:test:stable
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @tototrinh , @hhtank ,

Thanks for submitting this pull request. I'm still testing the changes.

Meanwhile, I think we should avoid major version bump, by deprecating the old `modules/apps/portal-background-task/portal-background-task-api/src/main/java/com/liferay/portal/background/task/constants/BackgroundTaskContextMapConstants.java` class. As I see, something similar has been done when https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/backgroundtask/BackgroundTaskConstants.java was moved to https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/backgroundtask/constants/BackgroundTaskConstants.java

Also, the https://github.com/liferay/liferay-portal/tree/master/portal-kernel/src/com/liferay/portal/kernel/backgroundtask/constants package already exists, so `BackgroundTaskContextMapConstants` can be placed there.

Can you please do these changes?

Thanks,
Vendel

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:sf
ci:test:stable
ci:test:staging

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:sf
ci:test:stable
ci:test:staging

**Comment by hhtank** [comment]
Hi @vendeltoreki,
I have pushed the changes following up your comment. Can you help take another look into this PR?
Thanks a lot for your help!

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Forwarding: https://github.com/brianchandotcom/liferay-portal/pull/130595

**Pull request closed without merging**
