### PR TITLE
LPS-161393 Include the 'doAsUserId' so the session tree click is saved to the correct user's portal preferences

### PR DESCRIPTION
**Pull request by jonathanmccann**
I wasn't sure who owned this module or file but since it was discovered utilizing Staging I thought it made sense to start with your team. Please let me know your thoughts or if there is a better team to review this change.

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @jonathanmccann ,

Interesting issue, I like the solution.

I'm summoning @zsigmondrab , just in case he has other ideas about the expected behaviour.
In the meantime I'm assigning the LPS to @gaborlovasdotcom so he can QA this.

Best,
Tamas

**Comment by JoyceWang08211** [comment]
Failures in ci:test:staging are not related to the current change.

**Comment by benjaminclement7** [comment]
Hello @moltam89 & @zsigmondrab,
Any updates on this one?

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
