### PR TITLE
LPS-190360 - As a Site Administrator I would like to see Staging recommendation before publishing

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190360](https://liferay.atlassian.net/browse/LPS-190360)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Review by vendeltoreki — COMMENTED** [review]
The code looks good to me. Just make sure to separate the commits:
* JSP code changes
* Language file changes
* Feature flag
We can ignore the discussed source format errors until it's fully resolved and it produces code that is actually working.

**Comment by DaniSzimko** [comment]
continue on https://github.com/liferay-staging/liferay-portal/pull/420

**Pull request closed without merging**
