### PR TITLE
LPS-190736 - As a Site administrator I would like to be notified if the staging process may take some time

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190736](https://liferay.atlassian.net/browse/LPS-190736)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci;test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Review by vendeltoreki — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/449

**Pull request closed without merging**
