### PR TITLE
LPS-174431 Site template friendly URL collision - edit site template page

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPS-174431](https://issues.liferay.com/browse/LPS-174431)
[LPS-174434](https://issues.liferay.com/browse/LPS-174434)

Use feature flags to enable these features:
```
feature.flag.LPS-174431=true
feature.flag.LPS-174434=true
```

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Meanwhile, I added commit https://github.com/liferay-staging/liferay-portal/pull/265/commits/dd05de3a2c698742935f86c2692b50446eef02c4 to fix AC-3 by adding a link to the page in the warning message.
Also, rebased to latest master to fix `portal.properties` conflict.

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
> 1. [PGStaging#ActivateRemoteStaging](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/338235//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_ActivateRemoteStaging_)

@vendeltoreki Regression found. Cannot add site template page without feature flag.
Steps to reproduce:
1. Create a site template: ST1
2. Navigate to ST1 and add a new page to ST1, name it as Page1

Expected Results: Page1 should be added successfully.
Actual Results: Cannot add site template page. The following error occurs in browser console:
`caught (in promise) SyntaxError: Unexpected end of JSON input
    at ?browserId=chrome&minifierType=js&languageId=en_US&t=1682043338076&/o/js/resolved-module/layout-admin-web@5.0.134/js/AddLayout.js:1:868
(`

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
The above regression is resolved and no more regression was found.
cc @vendeltoreki

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
[Semantic versioning issue](https://testray.liferay.com/reports/production/logs/2023-04/test-1-34/test-portal-acceptance-pullrequest(master)/3979/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0) was found in relevant run.
`clean-up-java-processes:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh
[stopwatch] [run.batch.test.setup: 21:40.379 sec]
     [echo] run.batch.test.action.start.timestamp: 04-26-2023 20:03:11:348 PDT
     [echo] Checking for baseline log files.
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 105.1.0
[beanshell] 
[stopwatch] [run.batch.test.action: 4.720 sec]
     [echo] Semantic versioning is incorrect.
      [get] Getting: http://test-1-36/job/test-portal-acceptance-pullrequest-downstream(master)/491172//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230426200316069.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230426200316069.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1751131529.properties`
@vendeltoreki Could you please fix this error? Thx

**Comment by JoyceWang08211** [comment]
No more regression was found. The only suspicious failure [PGStagingWithVersioning#AssertStagingVariationInfo](https://testray.liferay.com/home/-/testray/case_results/2282260806) passed locally.

**Comment by JoyceWang08211** [comment]
Hi @melodywu Could you please fix the failing relevant test cases in https://issues.liferay.com/browse/LRQA-80397? Thx
cc @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
> [Semantic versioning issue](https://testray.liferay.com/reports/production/logs/2023-04/test-1-34/test-portal-acceptance-pullrequest(master)/3979/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0) was found in relevant run. `clean-up-java-processes: [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh [stopwatch] [run.batch.test.setup: 21:40.379 sec] [echo] run.batch.test.action.start.timestamp: 04-26-2023 20:03:11:348 PDT [echo] Checking for baseline log files. [echo] [echo] ## [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log [echo] ## [echo] [beanshell] [Baseline Warning] Bundle Version Change Recommended: 105.1.0 [beanshell] [stopwatch] [run.batch.test.action: 4.720 sec] [echo] Semantic versioning is incorrect. [get] Getting: http://test-1-36/job/test-portal-acceptance-pullrequest-downstream(master)/491172//consoleText [get] To: /opt/dev/projects/github/liferay-portal/20230426200316069.txt [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230426200316069.txt [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1751131529.properties` @vendeltoreki Could you please fix this error? Thx

Please feel free to forward the PR after the Semantic versioning issue is resolved.
@vendeltoreki and @gaborlovasdotcom

**Comment by vendeltoreki** [comment]
Hi @JoyceWang08211 ,

I force-pushed commit https://github.com/liferay-staging/liferay-portal/pull/265/commits/8f8d0b5bd4003a19708f1eefe73dca41f8210a26 on the latest master. Seems like the previous semver error was fixed by https://github.com/liferay/liferay-portal/commit/3f8279257a7c6694ca11848a592294a5f2ad2fe6 on `portal-kernel/bnd.bnd`, now the build only modified `portal-impl/bnd.bnd`.

**Comment by vendeltoreki** [comment]
@JoyceWang08211 , @gaborlovasdotcom , I think we can discard this PR, as [other changes](https://issues.liferay.com/browse/LPS-174431?focusedCommentId=2898550&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2898550) just overwrote or deleted most of the files I was working on, so I will have to resend everything anyways.

**Comment by JoyceWang08211** [comment]
Hi @vendeltoreki, thanks for the info. I closed the current PR. Please feel free to let me know when the new PR is ready for testing.

**Pull request closed without merging**
