### PR TITLE
LPS-190015 - As a Site administrator I would like to manually select the web contents to publish

### PR DESCRIPTION
**Pull request by vendeltoreki**
Forwarding from: https://github.com/liferay-staging/liferay-portal/pull/432

cc: @DaniSzimko

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by martonakarczub** [comment]
ci:forward:force

**Pull request closed without merging**
