### PR TITLE
LRQA-76629

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-76629

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:staging

**Comment by weller0246** [comment]
ci:test:data-engine:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
@gaborlovasdotcom it has the same fix as the other reviewed PR, please review and forward if it is good,
thx

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
@weller0246  Please fix the ticket IDs in the commit title's

**Pull request closed without merging**
