### PR TITLE
LPS-196863 The documents and media URL of Image Fragment is not correctly processed when publishing from Staging to Live

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-196863

This is a regression caused by [LPS-187526](https://liferay.atlassian.net/browse/LPS-187526), in that LPS we added a new validation `_isExternalUrl` that checks if the URL points to an external server.

The problem with that method is it only validates URLs from HTML or Creole formats: `href='xxx'`, `src='xxx'`, `{{xxx}}`, `[[xxx]]` but the Image Fragment configuration stores this JSON configuration:
> {"com.liferay.fragment.entry.processor.editable.EditableFragmentEntryProcessor":{"image-square":{"defaultValue":"","config":{"alt":{"en_US":""},"imageConfiguration":{}},"en_US":{"classNameId":28902,"classPK":"123964","fileEntryId":"123964","title":"file1821253941895","url":"/documents/d/lpp-50905-staging/file1821253941895?imagePreview=1"}}},"com.liferay.fragment.entry.processor.freemarker.FreeMarkerFragmentEntryProcessor":{"imageSize":"w-100"}}

So in this case we have to check the `"url":"xxx"` pattern.

To solve this bug, I have created a new `_isJSONReference` method, that:

1. Finds the previous ocurrence of the "**url"** text, with quotes, as this is the JSON attribute
2. With the found position, it checks that the fragment follows the JSON syntax, as it could be a "url" text in other context. To do this, we use the regex `\"[^"\\\\]*\"\s*:\s*\"`, as you can have a different number of spaces, tabs or new line characters, for example, following formats are correct: `"url":"xxx"`, `"url": "xxx"`, `"url"   :   "xxx"`

I have also updated the dl_references.txt and dl_references_file_friendly_urls.txt files to cover these JSON cases with the DefaultExportImportContentProcessorTest test

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @liferay-staging @vendeltoreki 

Do you have any update about this PR?

Can we deliver this code as an SDH to the customer?

Regards,
Jorge

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

Sorry for the delay. I think the SDH can be delivered to the customer.

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
No regression was found.
cc @vendeltoreki

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
