### PR TITLE
[TECHNICAL SUPPORT] LPS-144573 Web Content with URL link that only has locale cannot be published due to wrong layout reference validation

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-144573](https://issues.liferay.com/browse/LPS-144573)

I am not a 100% sure if we should allow the usage of relative urls that only contain the locale, as its not really a reference to the main page, we simply just assume the intent. However I handle this scenario in my solution.
However these urls will be replaced to a relative url pointing to the "main" page after export.

Please review it.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Forwarding to: https://github.com/liferay-echo/liferay-portal/pull/6835

**Pull request closed without merging**
