### PR TITLE
LRQA-82895 | Master

### PR DESCRIPTION
**Pull request by GergoMathe**

### CODE REVIEW

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by GergoMathe** [comment]
ci:test:SitetemplatesStaging:nocompile

**Comment by GergoMathe** [comment]
ci:test:staging

**Comment by GergoMathe** [comment]
ci:test:staging

**Comment by GergoMathe** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
Test passed on Jenkins. LGTM.
https://testray.liferay.com/home/-/testray/case_results/2423554760

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
