### PR TITLE
LPS-170348 Store Changeset PortletPreferences against the correct plid

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-170348](https://issues.liferay.com/browse/LPS-170348)

This fixes an issue where the portletPreferences for the Changeset Portlet can get stored against the wrong plid. I actually wasn't sure how to test this issue in a user-visible way in master because the behavior in master is that we don't store empty PortletPreferences in the database at all (which is different from 7.3 and 7.2), and I wasn't sure how to make it generate a non-empty PortletPreferences for the Changeset Portlet.

I did test this change in 7.2 and verified that it fixed a user-visible bug there, which you can read in the Steps to Reproduce of [LPS-170348](https://issues.liferay.com/browse/LPS-170348).

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I've started reviewing the changes and tried to dig down to the root cause. I might be wrong but as I see, [LPS-86238](https://issues.liferay.com/browse/LPS-86238) fixed the issue in master [here](https://github.com/liferay/liferay-portal/blame/d72a0957d9a440f6522e9fb102fe08a049ecc0a9/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletImportControllerImpl.java#L355). It uses the correct `plid`, that was retrieved from `PortletDataContext` before the actual import is executed.
Do you think it's possible to (partially) backport [LPS-86238](https://issues.liferay.com/browse/LPS-86238) to 7.2.x to fix this issue?

**Comment by mbowerman** [comment]
Hi @vendeltoreki,

Sorry, I did not have time to test this today. I'll try it again tomorrow.

**Comment by mbowerman** [comment]
Hey @vendeltoreki, you were right, [LPS-86238](https://issues.liferay.com/browse/LPS-86238) fixes the issue. Let's treat this as a 7.2.x-specific bug that will be solved by a partial backport of [LPS-86238](https://issues.liferay.com/browse/LPS-86238) (technically we cannot backport it directly since it is a Technical Task ticket. Also the logic is a bit different in 7.2.x, so many of the commits are not applicable there.)

I've sent you a new pull request here: https://github.com/vendeltoreki/liferay-portal-ee/pull/50

**Pull request closed without merging**
