### PR TITLE
LPS-149713

### PR DESCRIPTION
**Pull request by mbowerman**
When the scopeType is "company", we should use the groupId of the original article rather than reusing the scopeGroupId. This is because scopeType "company" isn't necessarily referencing an article on the Global Site; the article could still be on the Staging/Export Site. And we don't want to duplicate the article onto the Global Site in that case; it should be published to the Live/Import Site instead.

Please let me know if you have any questions.

https://issues.liferay.com/browse/LPS-149713

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
> One of my colleagues couldn't reproduce this in 7.3 SP3, if it's a relatively fresh regression, it would be nice to know what caused it.

I don't think it's a regression, I think it's dependent on the order that the import happens in.

If the WCD portlet is imported _before_ the article, then the article is imported as a reference from the WCD portlet, which causes this bug.

On the other hand, if the article is imported before the WCD portlet, then the article is imported on its own, which doesn't cause this bug.

The import order doesn't always seem to be clearly defined, and I think it can change based on very minor factors, so I suspect that this is why it's being reproduced inconsistently.

> I wanted to see if it's a general problem with display portlets where we have the scope selector, but Wiki Display works differently. When I select the global scope, the page is not displayed anymore from the site scope.
> 
> I tend to think that the Wiki Display behaviour is better, I don't really understand why the Web Content Display still shows the Site scoped content, when the scope was set to Global.

This is a good point. I wonder if it's a bug that the WCD portlet still allows you to select Site content even on the Global scope. We may need to get the Echo team involved to discuss this.

> Also I feel like that the new code should be rather added to JournalContentExportImportPortletPreferencesProcessor, because it's a Web Content Display specific issue, the Web Content Display modifies the scope.

We could do this, but my fear is it is more likely to cause regressions, if there are other dependencies of the WCD portlet that _should_ be imported into the Global Site. I'm not sure if it's possible for the WCD portlet to have other dependencies besides the article though.

**Comment by moltam89** [comment]
Oh, so it's the order. It makes sense, probably I haven't followed the reproductions steps carefully enough last week and turned on staging before I created the article.

I understand your concerns about my suggested way of solving the bug, I'll need to spend more time on this if necessary.

Let's see what the Echo team says about the expected behaviour.

**Comment by moltam89** [comment]
Hi @mbowerman ,

If I understand it correctly from the PTR, LPS-96195 will be fixed instead of this ticket.

Can we close this PR and the related LPS?

Thanks,
Tamas

**Comment by mbowerman** [comment]
Sure, we can close it now. We will work on fixing [LPS-96195](https://issues.liferay.com/browse/LPS-96195)

**Pull request closed without merging**
