### PR TITLE
LPS-185572 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-185572

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
ExportImportValidation#VerifyURLPatternCouldConfiguredByWebId passed on Jenkins:
https://testray.liferay.com/home/-/testray/case_results/2362271867

cc @gaborlovasdotcom

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
Sent to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/137010

**Pull request closed without merging**
