### PR TITLE
[TS] LPS-143777 | missing test

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-143777
Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
I forced push the branch to fix the sf issue.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:staging

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
