### PR TITLE
LPS-172531 Add classNameIds and sort, move Comparator

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-172531](https://issues.liferay.com/browse/LPS-172531)

This PR fixes the RuntimeException: Unable to get class name from id 0 error, by adding the classNameIds to the AssetListEntrySegmentsEntryRel table's typeSettings, which are required to export contents successfully. I moved a comparator class to the asset-list-api module, to make it reusable elsewhere. This issue is blocking [this](https://issues.liferay.com/browse/LPS-176242) LPS, so this PR does not fix completely the staging on Masterclass site.

If everything seems fine after checking the code, please forward the PR to the @pt-liferay-solutions

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:close

**Pull request closed without merging**
