### PR TITLE
LPS-178889 Reset skipMerge after each layoutSet

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:test:staging test failures are not connected to the PR.

**Comment by moltam89** [comment]
ci:forward

**Comment by moltam89** [comment]
Rebased and resent here:
https://github.com/liferay-staging/liferay-portal/pull/270

**Pull request closed without merging**
