### PR TITLE
LRQA-79275 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-79275

### CODE REVIEW

**Review by gaborlovasdotcom — APPROVED** [review]
Very nice solution, LGTM!

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 , please review the SF issues, thanks!

**Comment by JoyceWang08211** [comment]
I will fix the SF issue, sorry

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
