### PR TITLE
LPS-178088 - As a Site Administrator, I want to have a better reference in error reports where the site information is involved

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-178088](https://issues.liferay.com/browse/LPS-178088) Added a referenceGroupId property to the MissingReference class + modified the JSONObject to include the groupID of the reference's environment

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Review by vendeltoreki — APPROVED** [review]
I've checked the changes, tested locally, and it seems like it's working as expected. Approved.

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
No regression was found among ci:test:staging and ci:test:relevant runs.

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward

**Comment by DaniSzimko** [comment]
@JoyceWang08211 Could you please review the relevant test results? Thank you.

**Comment by melodywu** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/302

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/302

**Pull request closed without merging**
