### PR TITLE
LPS-190015 - As a Site administrator I would like to manually select the web contents to publish

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190015](https://liferay.atlassian.net/browse/LPS-190015)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Review by vendeltoreki — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:forward

**Comment by zsigmondrab** [comment]
ci:forward:force

**Pull request closed without merging**
