### PR TITLE
LPS-151050

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-151050

### CODE REVIEW

**Comment by mbowerman** [comment]
The test failure "testSetImportDataElementCacheEnabled" looks like it may be related. I'll take a look.

**Comment by mbowerman** [comment]
I pushed up a new commit that should fix the test.

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:stable - 23 out of 25 jobs passed
> ### ❌ ci:test:relevant - 23 out of 26 jobs passed in 1 hour 39 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3117) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1307401_2919
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [90bf9de8c848cdfdd8641ace6dcb0f67cdf342ad](https://github.com/liferay/liferay-portal/commit/90bf9de8c848cdfdd8641ace6dcb0f67cdf342ad)
> 
> #### Upstream Comparison:
> Branch GIT ID: [d0af80528f382349ab73476476c6ca3e135b2c37](https://github.com/liferay/liferay-portal/commit/d0af80528f382349ab73476476c6ca3e135b2c37)Jenkins Build URL: [Acceptance Upstream DXP (master) #3116](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3116)
> 
> **ci:test:stable - 23 out of 25 jobs PASSED**
> **ci:test:relevant - 23 out of 26 jobs PASSED**
> ##### For more details click [here](https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2919/jenkins-report.html).
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/457996/)###### Job Results:7 Tests Passed.1 Test Failed.1. [AXIS_VARIABLE=3 #457996](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/457996//consoleText)1. [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3/457996//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7413_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2919/functional-upgrade-tomcat90-mysql57-jdk8/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7413/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2919/functional-upgrade-tomcat90-mysql57-jdk8/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7413/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2919/functional-upgrade-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz)
> 
> **Failures in common with [acceptance upstream results](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [d0af805](https://github.com/liferay-staging/liferay-portal/commit/d0af80528f382349ab73476476c6ca3e135b2c37):**

The unique failure of PortalSmokeUpgrade#ViewPortalSmokeArchive7413 is due to [LPS-145925](https://issues.liferay.com/browse/LPS-145925), not related to the current PR.

**Comment by JoyceWang08211** [comment]
> 

The above functional failures should not related to the current PR, they are passed on the previous [ci:test:staging run](https://github.com/liferay-staging/liferay-portal/pull/44#issuecomment-1089661447).

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:staging - 9 out of 13 jobs passed in 2 hours 7 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3117) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1267401_2568
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [90bf9de8c848cdfdd8641ace6dcb0f67cdf342ad](https://github.com/liferay/liferay-portal/commit/90bf9de8c848cdfdd8641ace6dcb0f67cdf342ad)
> 
> #### Upstream Comparison:
> Branch GIT ID: [d0af80528f382349ab73476476c6ca3e135b2c37](https://github.com/liferay/liferay-portal/commit/d0af80528f382349ab73476476c6ca3e135b2c37)Jenkins Build URL: [Acceptance Upstream DXP (master) #3116](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3116)
> 
> **ci:test:staging - 9 out of 13 jobs PASSED**
> ##### For more details click [here](https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2568/jenkins-report.html).
> #### Failures unique to this pull:
> 1. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/344649/)###### Job Results:87 Tests Passed.5 Tests Failed.1. [AXIS_VARIABLE=0 #344649](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/344649//consoleText)1. [LocalFile.PGStaging#ActivateDeactivateStagingLocalLiveDM](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/344649//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_ActivateDeactivateStagingLocalLiveDM_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/0/LocalFile.PGStaging_ActivateDeactivateStagingLocalLiveDM/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/0/LocalFile.PGStaging_ActivateDeactivateStagingLocalLiveDM/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/0/jenkins-console.txt.gz)2. [AXIS_VARIABLE=18 #344649](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18/344649//consoleText)1. [LocalFile.Staging#ValidateFriendlyURLWithSpecialCharacters](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=18/344649//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Staging_ValidateFriendlyURLWithSpecialCharacters_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/18/LocalFile.Staging_ValidateFriendlyURLWithSpecialCharacters/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/18/LocalFile.Staging_ValidateFriendlyURLWithSpecialCharacters/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/18/jenkins-console.txt.gz)3. [AXIS_VARIABLE=2 #344649](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/344649//consoleText)1. [LocalFile.PGStaging#DeactivateLocalStaging](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/344649//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_DeactivateLocalStaging_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_DeactivateLocalStaging/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_DeactivateLocalStaging/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/jenkins-console.txt.gz)2. [LocalFile.PGStaging#LayoutScope](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/344649//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_LayoutScope_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_LayoutScope/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_LayoutScope/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/jenkins-console.txt.gz)3. [LocalFile.PGStaging#PublishLayoutIconDeletion](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/344649//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_PublishLayoutIconDeletion_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_PublishLayoutIconDeletion/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_PublishLayoutIconDeletion/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/2/2/jenkins-console.txt.gz)
> 2. ##### [test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/480213/)###### Job Results:48 Tests Passed.4 Tests Failed.1. [AXIS_VARIABLE=0 #480213](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/480213//consoleText)1. [LocalFile.StagingUsecaseWithRoles#StagingLocalLiveWorkflow](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/480213//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithRoles_StagingLocalLiveWorkflow_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithRoles_StagingLocalLiveWorkflow/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithRoles_StagingLocalLiveWorkflow/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/jenkins-console.txt.gz)2. [LocalFile.StagingUsecaseWithRoles#UpdateAndDeleteWebContentCommentOnLiveSite](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/480213//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithRoles_UpdateAndDeleteWebContentCommentOnLiveSite_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithRoles_UpdateAndDeleteWebContentCommentOnLiveSite/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.StagingUsecaseWithRoles_UpdateAndDeleteWebContentCommentOnLiveSite/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/0/jenkins-console.txt.gz)2. [AXIS_VARIABLE=2 #480213](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/480213//consoleText)1. [LocalFile.StagingUsecaseWithVersioning#StagingPageLogo](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/480213//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_StagingPageLogo_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingPageLogo/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/2/LocalFile.StagingUsecaseWithVersioning_StagingPageLogo/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/2/jenkins-console.txt.gz)3. [AXIS_VARIABLE=5 #480213](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5/480213//consoleText)1. [LocalFile.StagingUsecaseWithVersioning#ViewChildPageNameViaLocalizedPage](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5/480213//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUsecaseWithVersioning_ViewChildPageNameViaLocalizedPage_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/5/LocalFile.StagingUsecaseWithVersioning_ViewChildPageNameViaLocalizedPage/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/5/LocalFile.StagingUsecaseWithVersioning_ViewChildPageNameViaLocalizedPage/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2568/functional-tomcat90-mysql57-jdk8/5/5/jenkins-console.txt.gz)
> 3. ##### [test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43904/)###### Job Results:351 Tests Passed.1 Test Failed.1. [AXIS_VARIABLE=1 #43904](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/43904//consoleText)1. [com.liferay.staging.test.StagingDataPortletPreferencesTest.testWikiDisplayDataPortletPreferences](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/43904//testReport/com.liferay.staging.test/StagingDataPortletPreferencesTest/testWikiDisplayDataPortletPreferences)```
>          org.junit.ComparisonFailure: expected:<56[422]> but was:<56[364]>
>            at org.junit.Assert.assertEquals(Assert.java:117)
>            at org.junit.Assert.assertEquals(Assert.java:146)
>            at com.liferay.staging.test.StagingDataPortletPreferencesTest.testWikiDisplayDataPortletPreferences(StagingDataPortletPreferencesTest.java:309)
>            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>            at java.lang.reflect.Method.invoke(Method.java:498)
>            at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
>            at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>            at org.junit.rules.RunRules.evalua...
>          ```
> 
> **Failures in common with [acceptance upstream results](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [d0af805](https://github.com/liferay-staging/liferay-portal/commit/d0af80528f382349ab73476476c6ca3e135b2c37):**

The above functional failures should not related to the current PR, they are passed on the previous [ci:test:staging run](https://github.com/liferay-staging/liferay-portal/pull/44#issuecomment-1089661447).

**Comment by JoyceWang08211** [comment]
Need to validate PGStaging#LayoutScope and StagingUsecaseWithVersioning#StagingPageLogo on local. Working on this.

**Comment by JoyceWang08211** [comment]
> PGStaging#LayoutScope and StagingUsecaseWithVersioning#StagingPageLogo

I've run the above failed functional testcases on local by building portal based on the current PR. All the above testcases are passed on local. 

cc @moltam89 and @gaborlovasdotcom

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I'm checking this pull request locally and the changes seem to be working correctly. I think we can forward if the tests are ok.

Thanks,
Vendel

**Comment by AngeloJ** [comment]
@vendeltoreki, since it appears that QA passed it in the message above can you forward this review.

**Comment by vendeltoreki** [comment]
Forwarding to https://github.com/brianchandotcom/liferay-portal/pull/115903

**Pull request closed without merging**
