### PR TITLE
LPS-185081 Implementation of feature to allow whitelisting URL patterns during content validation

### PR DESCRIPTION
**Pull request by mbowerman**
Hello Staging team,

I am pre-emptively sending this implementation of the Story ticket [LPS-184978](https://issues.liferay.com/browse/LPS-184978). I checked all the listed Acceptance Criteria there and it passes all of them. I did change the verbiage of some things in ways that I thought were more clear and consistent with how similar messages were worded in Liferay.

I say "pre-emptively" because I have not yet hidden this feature behind a feature flag as requested. However, I wanted to get your review of it first. I was not sure how to hide the new configuration behind a Feature Flag, and I reached out in a private Slack channel for assistance with this. In fact, in my view, adding a Feature Flag for this almost feels redundant to me, because we are already adding a new Configuration for this, and the behavior will be the same as it was previously unless the new Configuration is modified. So in my mind, the new Configuration itself almost serves as a sort of "Feature Flag" already.

Story ticket [LPS-184978](https://issues.liferay.com/browse/LPS-184978)
Technical Task ticket: [LPS-185081](https://issues.liferay.com/browse/LPS-185081)

Re-sent from https://github.com/liferay-staging/liferay-portal/pull/313

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

Thanks for submitting this request. I'm testing one commit I added: https://github.com/vendeltoreki/liferay-portal/commit/03c73539300ada6ca0a0d17080b2f871cd062109
It seems like it was always reading the old configuration values whenever I updated it. Basically, I had to save the config twice to actually take effect. I'm testing it now, and will forward the code, if it works correctly.

**Comment by mbowerman** [comment]
Hi @vendeltoreki,

I don't remember noticing the behavior that you mentioned, where you had to save the config twice. I think I would have noticed something like that. However, I was always testing it by updating the config in the UI (in System Settings or Instance Settings). I didn't think to test by deploying .config files. Is that how you were doing your testing?

Anyway I tested it again, this time with your commit https://github.com/vendeltoreki/liferay-portal/commit/03c73539300ada6ca0a0d17080b2f871cd062109 included, and I didn't notice the behavior (when updating it in System Settings). The config took effect immediately in my testing.

I've pushed up a new commit that adds some integration test cases. Could you please take a look when you get a chance?

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
> Hi @vendeltoreki,
> 
> I don't remember noticing the behavior that you mentioned, where you had to save the config twice. I think I would have noticed something like that. However, I was always testing it by updating the config in the UI (in System Settings or Instance Settings). I didn't think to test by deploying .config files. Is that how you were doing your testing?
> 
> Anyway I tested it again, this time with your commit [vendeltoreki@03c7353](https://github.com/vendeltoreki/liferay-portal/commit/03c73539300ada6ca0a0d17080b2f871cd062109) included, and I didn't notice the behavior (when updating it in System Settings). The config took effect immediately in my testing.
> 
> I've pushed up a new commit that adds some integration test cases. Could you please take a look when you get a chance?

Thanks, @mbowerman . I was testing the configuration on the UI too. It was strange, since it already saved the config to the database but `_configurationProvider.getCompanyConfiguration(..)` still returned the old values somehow.

Anyways, the tests work perfectly, thanks for implementing them.

I'm forwarding this to QA.

cc: @gaborlovasdotcom

**Review by vendeltoreki — APPROVED** [review]

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
