### PR TITLE
LPS-143531

### PR DESCRIPTION
**Pull request by mbowerman**
Original message from Roland:

> Hi @mbowerman
> 
> i made the changes you suggested here:
> 
> https://issues.liferay.com/browse/LPS-135087?focusedCommentId=2578029&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2578029
> 
> Please review it, and forward it to the product team.
> 
> **Reproduction Steps:**
> 
> Set up a Liferay bundle
> Go to Control Panel --> Content --> Web Content and add basic web content and add the following HTML in the source code of the content field:
> Hello This is the first line.
> 
> Second line, it contain relative a link to search page.
> 
> 3. Publish the content.
> **Actual Result:** The content is not published and the following error appears in the UI:
> 
> Error: Unable to validate referenced page with URL /en/search because the page group with URL /en cannot be found.
> No errors in the log or browser console.
> 
> **Expected Result:** The web content should be published successfully with no errors.
> 
> Thanks, Roland
> 
> https://issues.liferay.com/browse/LPS-143531

/cc @rolandpakai

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
