### PR TITLE
LPS-163451

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-163451

### CODE REVIEW

**Comment by moltam89** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:reevaluate:1297401_4674

**Comment by mbowerman** [comment]
Could we just manually forward this to Brian? This pull request clearly shouldn't be causing any test failures as all it's doing is fixing a typo...

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/123679

**Pull request closed without merging**
