### PR TITLE
LPS-187526 Missing reference during export-import due to a external site URL path collision with a local one to the site

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-187526

If you link a image from an external site in a web content but there is a content with the same URL path in the document library, you will get a missing reference during export-import operation to a different environment

**Root cause of the issue**
The root cause of the issue is LAR export operation doesn't consider the URL domain when handling missing references, so if you have two instances example01 and example02 and a site of example01 links to example02:

- http://example02:8080/documents/d/site01/black

The export operation only considers the URL path /documents/d/site01/black so if the same path exists in current instance, a missing reference will be generated. (for example with http://example01:8080/documents/d/site01/black)

**Solution**
To solve this problem I am using the code of `DLReferencesExportImportContentProcessor._validateDLReferences` that checks if a URL points to an external Liferay installation:

1. Commits a758fcd2f2346c94a780af7c2c783da3f833dd89 and fe0bb2f21e8d6e407b9c437b75d14c9cc16ef269 => Extract current logic of `DLReferencesExportImportContentProcessor._validateDLReferences` to a new `_isExternalUrl` method
2. Commit 98d3122538a5f986d2063f6b4ac933ae06514be2 => Use the new `_isExternalUrl` method in the export code logic `DLReferencesExportImportContentProcessor._replaceExportDLReferences` to avoid processing external URLs with the same URL path than a local resource
3. Commit c4dd2059300e5ed524acd42930c976e69040c395 => Remove the port from the URL before checking the hostname. Existing code was only working if the URL doesn't have any port (_http => 80, https => 443_) This wasn't so problematic in `DLReferencesExportImportContentProcessor._validateDLReferences` because that logic had access to `serviceContext.getThemeDisplay()`, but in Staging or Export/Import we are in a background task without that information, so it is better to fix the issue, removing the port before checking the hostname.

Let me know if you have any question

### CODE REVIEW

**Comment by DaniSzimko** [comment]
Hi @jorgediaz-lr , I reviewed your PR and I discovered that this solution does not work when the hostnames are the same (e.g., localhost) but the ports are different. I think the _portal.getPortalLocalPort(false) method can provide you the portal's port. Have you considered a solution where you compare the portal's port with the content's port to determine if it is an external URL?

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko 

I am going to review your comment about port validation.

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko 

I have added an additional commit c4dd2059300e5ed524acd42930c976e69040c395 that checks the URL port if it is present

Let me know if you have any question

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko 

Thanks for your message.

After analyzing the [dl_references_file_friendly_urls.txt](https://github.com/jorgediaz-lr/liferay-portal/blob/LPS-187526/modules/apps/export-import/export-import-test/src/testIntegration/resources/com/liferay/exportimport/internal/content/processor/test/dependencies/dl_references_file_friendly_urls.txt) file, it is true that existing code is not correctly handling the Creole links. It is not also correctly handling the href and src links with escaped quotes or without quotes.

I am working on solving it.

I will update the PR 

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko 

I have added following commits to solve the detected issues:

- commit 643e4bd25fd59c0a88760d89282c5e59b3c3dce4 fixes the StringIndexOutOfBoundsException  when searching the colon part
- commit 148699a0b0f370fcd07ffd8ba12d678ce7e39d2f extracts repeated code to new _isHTMLReference method
- commit 91e4b413f8e4fc2ae523280209b70e687ddf639b fixes DefaultExportImportContentProcessorTest.testExportDLReferences tests: Check references in creole format
- commit 53e4b6015b1695c1e72ecd9fd831c6c690f86178 fixes DefaultExportImportContentProcessorTest.testExportDLReferences tests: Modify _isHTMLReference method to check all cases: href=url, href='url', href="url", href=\'url\', href=\"url\", src=url, src='url', src="url", src=\'url\', src=\"url\"
- commit ba54df1c78a20c23f0838bd615adae129e918ad5 fixes DefaultExportImportContentProcessorTest.testExportDLReferences tests: replace WEB_ID with GROUP_PUBLIC_PAGES_VIRTUAL_HOST to test the URLs in the same way than DefaultExportImportContentProcessorTest.testExportLayoutReferencesWithContext or DefaultExportImportContentProcessorTest.testExportLayoutReferencesWithoutContext. (More information see layout_references.txt file). The existing WEB_ID constant is replaced with "liferay.com", that is an external host as the URL is not in the virtualhost table so the URL is not replaced after this LPS changes.

Let me know if you have any question

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko 

Do you have any update about this PR?

Thank you

**Comment by DaniSzimko** [comment]
Hi @jorgediaz-lr 

I asked our QA team to help me verify the relevant test failures. I had to review the ExportImport#ExportImportValidation testcase because it expects the import to be successful without any missing references when using an internal URL as reference to a DM that is subsequently deleted after the export. However, based on our discussion with @vendeltoreki , we believe this test needs to be modified to expect a failed import with missing references in this case.

After resolving the test failures, I think we can proceed to forward this PR.

**Comment by jorgediaz-lr** [comment]
Hi @DaniSzimko

Thanks for the information.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:export-import

**Comment by JoyceWang08211** [comment]
No regression was found.
cc @DaniSzimko

**Comment by DaniSzimko** [comment]
Thank you @JoyceWang08211 
I think we can forward this PR.

**Comment by DaniSzimko** [comment]
ci:forward

**Pull request closed without merging**
