### PR TITLE
LPS-168752 HR_431 Accessibility improvements for the Export/Import modal

### PR DESCRIPTION
**Pull request by veroglez**
Link to the ticket https://issues.liferay.com/browse/LPS-168752

Hi guys!

Some accessibility improvements have been done in the Export/Import modal:
- Remove all headers in the modal content. There should only be a single heading, the title of the modal (h1).
- Associate the correct label to the group to which each checkbox belongs.

Thanks in advance!

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
The following testcases keep failing:
[LocalFile.Staging#PublishViaPortletWithoutContent](https://testray.liferay.com/home/-/testray/case_results/2225683203)
[LocalFile.ExportImport#AssertStagingSystemSettingsInfo](https://testray.liferay.com/home/-/testray/case_results/2225683236)

**Comment by veroglez** [comment]
Hi @JoyceWang08211! yes, this is the expected behavior. The use of header H1 in the modal is a good practice since we are hiding the rest of the semantic page content. Our fix recommendation is in [this comment](https://issues.liferay.com/browse/LPS-168752?focusedCommentId=2832088&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2832088).

**Comment by JoyceWang08211** [comment]
> Hi @JoyceWang08211! yes, this is the expected behavior. The use of header H1 in the modal is a good practice since we are hiding the rest of the semantic page content. Our fix recommendation is in [this comment](https://issues.liferay.com/browse/LPS-168752?focusedCommentId=2832088&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2832088).

Hi @veroglez, Thanks for the info.
This PR looks good to me. @vendeltoreki

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
