### PR TITLE
LPS-78241 | master

### PR DESCRIPTION
**Pull request by Hiba-rahimi**

### CODE REVIEW

**Comment by Hiba-rahimi** [comment]
ci:test:relevant

**Comment by Hiba-rahimi** [comment]
ci:test:staging

**Comment by Hiba-rahimi** [comment]
@gaborlovasdotcom Hey! Could you please review ?

**Comment by vendeltoreki** [comment]
Closing. Forwarding on: https://github.com/liferay-staging/liferay-portal/pull/459

**Pull request closed without merging**
