### PR TITLE
LPS-195619, LRQA-83216

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
I'm working on adding additional test fixes.

**Comment by JoyceWang08211** [comment]
Continued in https://github.com/liferay-staging/liferay-portal/pull/428

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Pull request closed without merging**
