### PR TITLE
LPS-189191 As a Site Administrator I want to be able to configure staging to ignore previews and thumbnails during publish process

### PR DESCRIPTION
**Pull request by vendeltoreki**
forwarding from https://github.com/liferay-staging/liferay-portal/pull/372

[LPS-189191](https://liferay.atlassian.net/browse/LPS-189191) - added the includeThumbnailsAndPreviewsDuringStaging checkbox, added new properties to language.properties, added DisplayContext to render_controls.jsp which includes the condition regarding the Thumbnails and previews

cc: @DaniSzimko

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
The semantic versioning is incorrect:
`[exec] > Task :apps:export-import:export-import-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.exportimport.configuration             MINOR      2.2.0      2.2.0      2.3.0      VERSION INCREASE REQUIRED
     [exec] 	<   interface  com.liferay.exportimport.configuration.ExportImportServiceConfiguration
     [exec] 		+   method     includeThumbnailsAndPreviewsDuringStaging()
     [exec] 			+   access     abstract
     [exec] 			+   annotated  aQute.bnd.annotation.metatype.Meta$AD
     [exec] 				+   property   deflt='true'
     [exec] 				+   property   description='if-checked,-then-the-generated-previews-and-thumbnails-will-be-included-during-staging-process'
     [exec] 				+   property   name='include-thumbnails-and-previews-during-staging'
     [exec] 				+   property   required=false
     [exec] 			+   return     boolean
     [exec] [Baseline Warning] Bundle Version Change Recommended: 7.4.0`

No regression was found, most failures are due to https://liferay.atlassian.net/browse/LPS-191729.
cc @DaniSzimko and @vendeltoreki

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
