### PR TITLE
LPS-190176 Fix export/import issues with FriendlyURLEntries related to assets within the export scope

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-190176](https://liferay.atlassian.net/browse/LPS-190176)

I implemented the solution described by @vendeltoreki [here](https://github.com/liferay-staging/liferay-portal/pull/361#issuecomment-1634209688). I tested this and verified that it resolved the issue.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Regression:
1. Add a new site called Site Name with a public widget page in localhost:8080
2. Add a new site called Remote Site in localhost:9080
3. Enable remote staging between the above two sites
4. Add a web content entry and a blog entry in Site Name site
5. Navigate to site page of Site Name
6. Click Publish to Live button
7. Click Publish to Remote Live button directly  

Expected result: The publication should be successful.
Actual result: The publication failed due to DuplicateFriendlyURLEntryException.
`2023-07-13 17:52:21.859 ERROR [liferay/background_task-7][StagingServiceHttp:326] com.liferay.portal.kernel.exception.SystemException: java.lang.ClassNotFoundException: com.liferay.friendly.url.exception.DuplicateFriendlyURLEntryException
com.liferay.portal.kernel.exception.SystemException: java.lang.ClassNotFoundException: com.liferay.friendly.url.exception.DuplicateFriendlyURLEntryException
	at com.liferay.portlet.exportimport.service.http.StagingServiceHttp.publishStagingRequest(StagingServiceHttp.java:316) [portal-impl.jar:?]
	at com.liferay.exportimport.internal.background.task.LayoutRemoteStagingBackgroundTaskExecutor.execute(LayoutRemoteStagingBackgroundTaskExecutor.java:142) [bundleFile:?]
	at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:63) [bundleFile:?]
	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:41) [portal-kernel.jar:?]
	at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:72) [bundleFile:?]
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:124) [bundleFile:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.liferay.friendly.url.exception.DuplicateFriendlyURLEntryException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412) ~[catalina.jar:9.0.75]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220) ~[catalina.jar:9.0.75]
	at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:79) ~[com.liferay.shielded.container.impl.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at com.liferay.portal.kernel.util.AggregateClassLoader._loadClass(AggregateClassLoader.java:312) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.AggregateClassLoader.loadClass(AggregateClassLoader.java:266) ~[portal-kernel.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]`

**Comment by mbowerman** [comment]
Hello @JoyceWang08211, unfortunately I haven't been able to reproduce the regression that you mentioned.

I did have some questions about the steps:
* When I enable Remote Staging, am I supposed to check *Blogs* under the "Staged Content" heading in the staging configuration? (I tried it both ways, but it didn't reproduce either way.)
* In step 5, I assume that "Site Page" refers to the Widget Page we added in step 1. Is that right?

One thing I did differently than you (I think), is that I set up the Staging Site and Remote Live Site on the same bundle, but in different Virtual Instances. I had trouble starting up two bundles at the same time. I am not sure if this makes a difference.

I assume the stacktrace you posted is from the Staging bundle. Do you happen to have a stacktrace from the Live bundle when the issue is reproduced? I think that would be more informative, since the problem is occurring on the import (Live bundle) side.

@vendeltoreki Have you been able to reproduce the regression?

**Comment by JoyceWang08211** [comment]
> Hello @JoyceWang08211, unfortunately I haven't been able to reproduce the regression that you mentioned.
> 
> I did have some questions about the steps:
> 
> * When I enable Remote Staging, am I supposed to check _Blogs_ under the "Staged Content" heading in the staging configuration? (I tried it both ways, but it didn't reproduce either way.)
> * In step 5, I assume that "Site Page" refers to the Widget Page we added in step 1. Is that right?
> 
> One thing I did differently than you (I think), is that I set up the Staging Site and Remote Live Site on the same bundle, but in different Virtual Instances. I had trouble starting up two bundles at the same time. I am not sure if this makes a difference.
> 
> I assume the stacktrace you posted is from the Staging bundle. Do you happen to have a stacktrace from the Live bundle when the issue is reproduced? I think that would be more informative, since the problem is occurring on the import (Live bundle) side.
> 
> @vendeltoreki Have you been able to reproduce the regression?

Hi @mbowerman, the above issue can only be reproduced when publishing on the site page with default settings. I don't think this issue can be reproduced when enabling remote staging in one bundle.
Here is the [doc](https://liferay.atlassian.net/wiki/spaces/ENGSTAGING/pages/2145159503/Setting+up+remote+staging+in+local+machine) about how to set up remote staging with two bundles.  
I also uploaded a record of the completed reproduced steps and error logs of two bundles in [LPS-190176](https://liferay.atlassian.net/browse/LPS-190176).
Please let me know if you need any other help.

**Comment by mbowerman** [comment]
Hi @JoyceWang08211 Thank you very much for your help. I was able to reproduce the regression now.

Hi @vendeltoreki, I reproduced the regression, but I am not sure what the correct way to fix it is.

The regression is occurring because there is some validation logic in the `BlogsEntryLocalService#addEntry` method that checks if the FriendlyURLEntry already exists or not. Therefore, the BlogsEntry NEEDS to be imported _before_ the FriendlyURLEntry is imported, or else this validation logic will fail.

Before my changes, this was always happening because we exported the BlogsEntry as a dependency of the FriendlyURLentry.

After my changes, this is _supposed_ to always still happen, because even though we switched the dependency order, we included FriendlyURLEntry.class in the skipImportReferences for BlogsEntry. Unfortunately, however, when publishing a Changeset, the FriendlyURLEntry ends up being included in the root of the ChangesetPortletDataHandler's portlet-data.xml file. For example, for me, the `portlet-data.xml` file looked like this:
```
<ChangesetPortletDataHandler self-path="/group/34204/portlet/com_liferay_exportimport_web_portlet_ChangesetPortlet/34204/portlet-data.xml" group-id="34204">
  <JournalArticle>
    <staged-model group-id="34204" uuid="aba4229b-4aa9-22a0-6796-4dffb3b75120" article-resource-uuid="ccca62af-8171-54ee-1ef4-1fff28d158e1" cached="false" path="/group/34204/com.liferay.journal.model.JournalArticle/34426.xml" attached-class-name="" user-uuid="181bbd4a-b590-422d-9b29-1e5eedf1a8ae" asset-entry-priority="0.0">
      <references>
        <reference class-name="com.liferay.dynamic.data.mapping.model.DDMStructure" class-pk="33214" attached-class-name="com.liferay.journal.model.JournalArticle" group-id="20121" group-key="20096" live-group-id="20121" type="dependency" uuid="7134e5cc-c4b1-53a2-2310-58db81c43709" company-id="20096" preloaded="true" referenced-class-name="com.liferay.journal.model.JournalArticle" structure-key="BASIC-WEB-CONTENT" missing="true"/>
        <reference class-name="com.liferay.dynamic.data.mapping.model.DDMTemplate" class-pk="33218" attached-class-name="com.liferay.dynamic.data.mapping.model.DDMStructure" group-id="20121" group-key="20096" live-group-id="20121" type="dependency" uuid="df2dfeb6-575f-edeb-e848-c88b2e6866cf" company-id="20096" preloaded="true" referenced-class-name="com.liferay.dynamic.data.mapping.model.DDMStructure" template-key="BASIC-WEB-CONTENT" missing="true"/>
        <reference class-name="com.liferay.friendly.url.model.FriendlyURLEntry" class-pk="34429" attached-class-name="com.liferay.journal.model.JournalArticle" type="dependency" uuid="c91af00e-7978-e37d-c860-abce5b7b41e2" company-id="20096" missing="false"/>
      </references>
    </staged-model>
  </JournalArticle>
  <FriendlyURLEntry>
    <staged-model uuid="c91af00e-7978-e37d-c860-abce5b7b41e2" resource-class-name="com.liferay.journal.model.JournalArticle" mainEntry="true" path="/company/20096/com.liferay.friendly.url.model.FriendlyURLEntry/34429.xml" attached-class-name="com.liferay.journal.model.JournalArticle" asset-entry-priority="0.0"/>
    <staged-model uuid="e199a61b-4054-d0bd-9422-f1ca93a23639" resource-class-name="com.liferay.blogs.model.BlogsEntry" mainEntry="true" path="/company/20096/com.liferay.friendly.url.model.FriendlyURLEntry/34440.xml" attached-class-name="com.liferay.blogs.model.BlogsEntry" asset-entry-priority="0.0">
      <references>
        <reference class-name="com.liferay.blogs.model.BlogsEntry" class-pk="34438" group-id="34204" group-key="Site Name" live-group-id="34173" type="dependency" uuid="3af158fe-ca65-0313-ef21-189350389896" company-id="20096" missing="false"/>
      </references>
    </staged-model>
  </FriendlyURLEntry>
  <BlogsEntry>
    <staged-model group-id="34204" uuid="3af158fe-ca65-0313-ef21-189350389896" path="/group/34204/com.liferay.blogs.model.BlogsEntry/34438.xml" user-uuid="181bbd4a-b590-422d-9b29-1e5eedf1a8ae" asset-entry-priority="0.0"/>
  </BlogsEntry>
</ChangesetPortletDataHandler>
```
So, when it goes to import all the data from the PortletDataHandler.xml file, it imports the FriendlyURLEntry first, and then it imports the BlogsEntry. Because it imports the FriendlyURLEntry independently, at the root level, rather than importing it as a reference of the BlogsEntry.

Do you know what the correct solution for this is? Is there an easy way to prevent the FriendlyURLEntry from ending up in the root of the ChangesetPortlet, while still ensuring that it is exported as a reference of the BlogsEntry?

**Comment by vendeltoreki** [comment]
Hi @mbowerman , @JoyceWang08211 ,

Yes, now I see the issue, thanks for describing the details. The first thing I can think of is to modify [FriendlyURLEntryStagedModelDataHandler#doImportStagedModel(..)](https://github.com/liferay/liferay-portal/blob/00ef5f2e7195644ba90551d0c524b2cbb19be966/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/exportimport/data/handler/FriendlyURLEntryStagedModelDataHandler.java#L106), to validate whether the entity that we want to link the FriendlyURLEntry to actually exists. Since FriendlyURLEntry records can't exist just by themselves, they are always tied to some entity, so they can only be exported as a reference of that entity. One exception can be, when you only modify the friendly URL of something that already exists and only want to publish/export that modification.
There's an example on how to find staged model based on `classNameId` and `classPK`: https://github.com/liferay/liferay-portal/blob/c05b02279b79564a5a9dfbcbdd4191627fc251e2/modules/apps/export-import/export-import-changeset-web/src/main/java/com/liferay/exportimport/changeset/web/internal/portlet/data/handler/ChangesetPortletDataHandler.java#L281-L299
The only problem I see with this is that the PortletDataContext will assume that the FriendlyURLEntry is already imported, so my guess is that we also have to remove it from the processed items' list.

Unfortunately, reverting to the inverse-dependency would make the original scenario fail, so that's not really a good solution either.

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

I just found this one: https://github.com/liferay/liferay-portal/blame/05987206ad49cafb519170527f0a24f21f1e5032/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/service/impl/BlogsEntryLocalServiceImpl.java#L321
It seems like this problem happened in the past as well, and was solved in the `LocalService`, instead of the `StagedModelDataHandler`. So adding `isStagingInProcess()` would probably solve it.

**Pull request closed without merging**
