### PR TITLE
LPS-166286 As a Site Template Administrator, I want the propagation process run in the background

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-166286
https://issues.liferay.com/browse/LPS-166469

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM

**Comment by gaborlovasdotcom** [comment]
ci:forward:force

**Pull request closed without merging**
