### PR TITLE
LPS-164621 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LPS-164621](https://issues.liferay.com/browse/LPS-164621)

Continuing from https://github.com/liferay-staging/liferay-portal/pull/140

### CODE REVIEW

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
