### PR TITLE
LPS-142761

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Staging team,

I wasn't sure whether I should send this to you or Shuyang. Probably it would be good to have both of you review it.

Please see the description of [LPS-142761](https://issues.liferay.com/browse/LPS-142761) for details about the context of this fix and why it is necessary.

I thought about adding safeguards for thread-safety, but then I thought it wasn't necessary because, as I understand, the entire export process is handled within a single thread. Also, our existing code didn't seem to be thread-safe, so I figured it must not be necessary to make it thread-safe.

I tested this and saw that with 10,000 PDF documents, this fix improved the performance from about an hour to about 4 minutes (with the cache fully warmed up in both cases. Without the cache warmed up, the performance is much worse, takes about 30 minutes with this fix).

I also verified that the LAR could be imported successfully into another environment after exporting it with this fix deployed. 

I also tried setting `zip.export.max.bytes.allowed.in.memory` to a lower value (10485760), and verified via the debugger that the property was behaving as intended, and verified via importing it that the LAR was generated correctly.

Please let me know if you have any questions about this fix.

https://issues.liferay.com/browse/LPS-142761

### CODE REVIEW

**Comment by moltam89** [comment]
Sorry @mbowerman , we missed this PR.
 I'm starting the review.

**Comment by JoyceWang08211** [comment]
The above two failing tests are not related to the current PR. I'm working on the test-fix of these tests under:
https://issues.liferay.com/browse/LPS-136401
https://issues.liferay.com/browse/LPS-141841

**Comment by moltam89** [comment]
Hi @mbowerman ,

Sorry again for the slower response.

Finishing the export in 4minutes instead of an hour is quite impressive.
The fix looks good to me, but as you mentioned, probably Shuyang should make the final call.
 
I'm not sure about the impact of the fix on larger files.
Before the fix **Files.copy** was used, and after it will be **StreamUtil.toByteArray +  Files.write**, and I don't really know which one is more effective.

I tried to test a <2GB file, but the export failed for me with OutOfMemoryError, despite I increased the memory settings. It looks like the MAX_ARRAY_SIZE is exceeded in this case, I got a slightly different error message before and after the fix.

I can continue the investigation next weak, but I think Shuyang could finish this review  a lot faster and he'll be needed anyways to finalize the solution.

Best,
Tamas

Here are the before and after the fix error logs:
```
java.lang.OutOfMemoryError: null
	at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123) ~[?:1.8.0_261]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117) ~[?:1.8.0_261]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[?:1.8.0_261]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153) ~[?:1.8.0_261]
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253) ~[?:1.8.0_261]
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211) ~[?:1.8.0_261]
	at com.sun.nio.zipfs.ZipFileSystem$EntryOutputStream.write(ZipFileSystem.java:1588) ~[zipfs.jar:1.8.0_261]
	at java.nio.file.Files.copy(Files.java:2909) ~[?:1.8.0_261]
	at java.nio.file.Files.copy(Files.java:3027) ~[?:1.8.0_261]
	at com.liferay.portal.zip.ZipWriterImpl.addEntry(ZipWriterImpl.java:133) ~[portal-impl.jar:?]
	at com.liferay.exportimport.internal.lar.PortletDataContextImpl.addZipEntry(PortletDataContextImpl.java:492) ~[?:?]
	at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:319) ~[?:?]
	at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:114) ~[?:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:102) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.data.handler.base.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:80) ~[?:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.exportStagedModel(StagedModelDataHandlerUtil.java:170) ~[portal-kernel.jar:?]
	at com.liferay.document.library.internal.exportimport.staged.model.repository.FileEntryStagedModelRepository.lambda$getExportActionableDynamicQuery$1(FileEntryStagedModelRepository.java:188) ~[?:?]

Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at com.liferay.petra.io.unsync.UnsyncByteArrayOutputStream.<init>(UnsyncByteArrayOutputStream.java:37) ~[com.liferay.petra.io.jar:?]
	at com.liferay.petra.io.StreamUtil.toByteArray(StreamUtil.java:75) ~[com.liferay.petra.io.jar:?]
	at com.liferay.exportimport.internal.lar.PortletDataContextImpl.addZipEntry(PortletDataContextImpl.java:493) ~[?:?]
	at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:319) ~[?:?]
	at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:114) ~[?:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:102) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.data.handler.base.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:80) ~[?:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.exportStagedModel(StagedModelDataHandlerUtil.java:170) ~[portal-kernel.jar:?]
	at com.liferay.document.library.internal.exportimport.staged.model.repository.FileEntryStagedModelRepository.lambda$getExportActionableDynamicQuery$1(FileEntryStagedModelRepository.java:188) ~[?:?]
```

**Comment by mbowerman** [comment]
Hi @shuyangzhou,

Could you please take a look at this pull request when you get a chance? Please see the description of [LPS-142761](https://issues.liferay.com/browse/LPS-142761) for details about the context of this fix

**Comment by mbowerman** [comment]
Hi @tinatian,

Could you please take a look at this pull request when you get a chance since @shuyangzhou is on vacation? Please see the description of [LPS-142761](https://issues.liferay.com/browse/LPS-142761) for details about the context of this fix

**Comment by mbowerman** [comment]
Modified and re-sent at https://github.com/liferay-core-infra/liferay-portal/pull/34 after discussion with @tinatian

**Pull request closed without merging**
