### PR TITLE
[Story] LPS-190628 - As a Site Administrator I would like to be able to transfer Client Extension related portlets during staging process

### PR DESCRIPTION
**Pull request by JoyceWang08211**
[LPS-190628](https://liferay.atlassian.net/browse/LPS-190628)

cc @DaniSzimko

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
No regression was found from ci:test:staging run.

**Review by gaborlovasdotcom — APPROVED** [review]
Test case looks good to me.

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
The semantic versioning issue has been fixed under:
https://github.com/liferay/liferay-portal/commit/aeedd1b3964fe7292b1491c9cdede353fb499cf3

**Comment by JoyceWang08211** [comment]
No unique failures from relevant runs.

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward:force

**Pull request closed without merging**
