### PR TITLE
LRQA-84354 | master

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-84354](https://liferay.atlassian.net/browse/LRQA-84354)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by gaborlovasdotcom** [comment]
@JoyceWang08211 , could you please review the test failures for the reactivated tests?

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 , could you please review the test failures for the reactivated tests?

1. [LocalFile.ExportImportPortlet#CustomFieldDeletionViaImporting](https://testray.liferay.com/home/-/testray/case_results/2459237713?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2459232131%26testrayRunId%3D2459237698%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) still failed on Jenkins. 

2. I will investigate the failure of [LocalFile.StagingUsecaseWithVersioning#PublishPageRevisionWithPortletSet...](https://testray.liferay.com/home/-/testray/case_results/2459237877?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2459232131%26testrayRunId%3D2459237698%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) later.

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
