### PR TITLE
LPS-190064 - As a Site Administrator, I would like to see which web content was published in the summary, after a single asset publication

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190064](https://liferay.atlassian.net/browse/LPS-190064)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:reevaluate:1327401_1862

**Comment by JessieZhao0714** [comment]
The semantic versioning is incorrect while checking:
1. com.liferay.exportimport.kernel.lar
`[exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.exportimport.kernel.lar                MINOR      5.0.0      5.0.0      5.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.exportimport.kernel.lar.ManifestSummary
     [exec] 		+   method     addAssetTitle(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 		+   method     getStagedModelAssetTitle(java.lang.String)
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     getStagedModelAssetTitles()
     [exec] 			+   return     java.util.Map
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/121.0.0/55c0cd4bf8ef67ed35d7e345322e111a0dd25daf/com.liferay.portal.kernel-121.0.0.jar
     [exec] Gradle build finished at 2023-09-01 13:48:33.912.`

2. com.liferay.exportimport.constants
`[exec] > Task :apps:export-import:export-import-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.exportimport.constants                 MINOR      1.1.3      1.1.3      1.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.exportimport.constants.ExportImportBackgroundTaskContextMapConstants
     [exec] 		+   field      ASSET_TITLES
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   assetTitles
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 7.6.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.exportimport.api-7.5.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.exportimport.api/7.5.0/6ddc94e3d16b6ddcd3135cb11aa970440eebd470/com.liferay.exportimport.api-7.5.0.jar`

3. com.liferay.journal.constants
`[exec] > Task :apps:journal:journal-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.journal.constants                      MINOR      4.1.0      4.1.0      4.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.journal.constants.JournalArticleConstants
     [exec] 		+   field      ASSET_TITLE
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   assetTitle
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 33.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.journal.api-33.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.journal.api/33.0.0/944f34f6111e078284c2e7ed5e1f23a2ba38e1fd/com.liferay.journal.api-33.0.0.jar`

No regression was found.
cc @vendeltoreki and @gaborlovasdotcom

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Review by vendeltoreki — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:forward:force

**Pull request closed without merging**
