### PR TITLE
LPS-195619, LRQA-83216

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-195619
https://liferay.atlassian.net/browse/LRQA-83216
cc @BarbaraCabrera, @ealonso and @gaborlovasdotcom

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @JoyceWang08211, 

I think we can manual forward it, since the tests failures seems to be not related. What do you think?

**Comment by ealonso** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:stable - 29 out of 31 jobs passed in 1 hour 27 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [441efeede491d5dfb91fcbf7212db12813cb339f](https://github.com/liferay/liferay-portal/commit/441efeede491d5dfb91fcbf7212db12813cb339f)
> 
> **ci:test:stable - 29 out of 31 jobs PASSED**
> ##### For more details click [here](https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10275/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/370211//consoleText)1. [LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/370211//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7310_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10275/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7310/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10275/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7310/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10275/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7310/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10275/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3/jenkins-console.txt.gz) - [Failed 1 of last 11](https://testray.liferay.com/home/-/testray/case_results/2438953062/history)
> 
> #### For upstream results, click [here](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

The above error also occurs in ci:test:upgrade on the latest master. It's not related to current changes. I'll manually forward this PR.
cc @ealonso and @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
Sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/142061

**Pull request closed without merging**
