### PR TITLE
LRQA-71165 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-71165

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
I think the verb of the imperative sentence is in its original form instead of in the singular.
e.g.
task ("And: Adds an AP portlet to the second page and a priority metadata field to it") 

It's better to change as "task ("And: Add an AP portlet to the second page and a priority metadata field to it") "

cc @weller0246 and @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
LGTM

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
