### PR TITLE
LPS-140449 Uses alert to show the message, to avoid breaking the user interface

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
As discussed this on the slack thread, it can be confusing that the warning message pops up over and over again.

Probably a better solution could be to show a warning icon and display the message only when this icon is clicked.

This ticket will be added to one of the future staging sprints.

**Comment by moltam89** [comment]
ci:close

**Pull request closed without merging**
