### PR TITLE
[TS] LPS-164933 |SEO Title and Description of a Page is discarded if its name is changed while Staging and Page versioning is enabled

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-164933
Best,
Attila

### CODE REVIEW

**Comment by moltam89** [comment]
I'm still not sure if this is the final solution, there are several settings which cannot be saved, or cannot be reverted.
Something is fishy here, I think this should be investigated properly, to figure out which settings are not stored and why.

**Comment by ahika74** [comment]
Hi Team,

Do we have any update on this issue?

**Comment by moltam89** [comment]
cc @gaborlovasdotcom , @weller0246

**Comment by weller0246** [comment]
ci:forward

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by weller0246** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
Forwarded directly to BChan in https://github.com/brianchandotcom/liferay-portal/pull/125971

**Pull request closed without merging**
