### PR TITLE
LPS-166513

### PR DESCRIPTION
**Pull request by tototrinh**
Hi team,
Please help review this PR and leave your comment.
Ticket: https://issues.liferay.com/browse/LPS-166513
This is the implementation of the AC-1. AC-2 was already implemented and was merged into the Master.
We set the warning message at the top in Export Layou and Export Portlet views.
Thanks.
cc: @thabet91 @hhtank

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:staging

**Review by vendeltoreki — APPROVED** [review]
Approved: I tested the changes and the message shows up on both export forms

**Comment by laszlopap** [comment]
ci:forward

**Comment by laszlopap** [comment]
ci:forward:force

**Pull request closed without merging**
