### PR TITLE
LRQA-78634 | master

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-78634

### CODE REVIEW

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:lima:nocompile

**Comment by weller0246** [comment]
ci:test:document:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]
The staging test case: StagingUsecase#ViewPublishDMWithModifiedTitle still [fails](https://testray.liferay.com/home/-/testray/case_results/2089620315):
It seems we might need an additional wait for element for the AP#ASSET_EDIT

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
