### PR TITLE
[TS] LPS-160639

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Staging Team,

Can you help review this PR?

**Note:** The added integration test is for the scenario described in [LPS-150838](https://issues.liferay.com/browse/LPS-150838)
- BChan requested for an integration test when the fix was submitted for [LPS-150838](https://issues.liferay.com/browse/LPS-150838)
  - https://github.com/brianchandotcom/liferay-portal/pull/116348#issuecomment-1104011355
- I decided to change the ticket number to this newer one, since the ticket has been closed. 
  - Please let me know if you would like me to change the commit message back to the original ticket.

**Notes from @noornajj**

> https://issues.liferay.com/browse/LPS-160639
> 
> This is a regression bug caused by [LPS-150838](https://issues.liferay.com/browse/LPS-150838)
> The issue here is that blog entries don't get published to live when the blog portlet is scoped to the page. 
> 
> To fix this issue, I reverted the fix from LPS-150838 and changed the location of the fix to PortletDataContextImpl.importPortletPermissions. Here I changed the the target resource from scope group Id to the current group Id. 
> 
> This fix resolves both issues.

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by noornajj** [comment]
Hello,

Are there any updates for this PR?

Thank you

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
The unique failure of the ci:test:staging run is unrelated to the current changes.
cc @moltam89 and @vendeltoreki

**Comment by moltam89** [comment]
I'm starting the review.

**Comment by moltam89** [comment]
Hi guys,

I don't really understand the "Do not import portlet permissions when the portlet is scoped to a different group" commit.

What is the reason we don't want to import permissions if the portlet is scoped?
This doesn't seem right to me.

Thanks,
Tamas

**Comment by noornajj** [comment]
Hi @moltam89,

This relates back to the issue seen in [LPS-150838](https://issues.liferay.com/browse/LPS-150838)
When a page with a portlet, that is scoped to the Global site, gets imported to a new site, the Global permissions of the admin portlet get overwritten. 
The steps in the ticket explain the situation better.

**Comment by moltam89** [comment]
Hi @noornajj ,

Yeah, I saw the steps on [LPS-150838](https://issues.liferay.com/browse/LPS-150838), but I don't think we can make a general change because of a specific use case.
Before [LPS-150838](https://issues.liferay.com/browse/LPS-150838), we could scope a portlet and the permissions were exported/imported or published to Live, and I think we still want this feature.

Best,
Tamas

**Comment by noornajj** [comment]
Hi @moltam89,

This issue is a bit confusing so I want to make sure we are on the same page about which permissions. There are two types of permission related to this issue

- The permissions associated to the portlet/widget added to the page
- The portlet's admin permissions found by navigating to Sidebar Menu -> Content and Data -> Portlet (ex: Documents and Media)

I am referring to the second type of permissions. Here is a more detailed scenario of what's going on: 
- Create site1
- Go to Content and Data -> Documents and Media and change the Home Folder permissions
- Add a documents and media portlet on a page scoped to Global
- Export the site with permissions
- Import the LAR file into site2 with permissions
- Go to site2 Content and Data -> Documents and Media and check the Home Folder Permissions
- The permissions match site1 as expected
- Go to the Global site -> Content and Data -> Document and Media and check the Home Folder Permissions
- The permissions here also got altered which is not expected

To me, it doesn't make sense that the import alters the Global site's permissions if a portlet on a page is scoped to Global. My fix only prevents the last step from happening but the permissions still get imported and exported to the new site.

Are you saying that the Global site should be updated?

**Comment by moltam89** [comment]
Hi @noornajj ,

Thanks for the detailed explanation.

You're absolutely right, we don't want to update the Global Site with the permissions from the Site.

On the other hand, I think we should handle page scopes as well.
It looks like this did not work even before  [LPS-150838](https://issues.liferay.com/browse/LPS-150838), because the Site's permissions were exported, instead of the page scoped group.

Could you please check how page scoped permissions are exported/imported?

Thanks,
Tamas

**Comment by noornajj** [comment]
Hello @moltam89,

Can you please explain or provide steps on what the page scoped permissions are? Are you referring to the permissions that are set to the portlet on the page from edit mode?

**Comment by moltam89** [comment]
Hi @noornajj ,

Instead of scoping the portlet to Global, we can also scope it to the page, which creates a Group, where we can set Home Folder Permissions the same way as in the Site.

Best,
Tamas

image
image

**Comment by noornajj** [comment]
Thank you @moltam89 for the clarification. I was not aware that the Default Scope for Content and Data could be changed that way.
I will test this scenario with and without my changes and let you know the results.

**Comment by noornajj** [comment]
Hello @moltam89 

Sorry for the late reply, I was busy with other tasks.

So, I was able to confirm that the page scoped permissions are not being exported. This issue was occurring even before [LPS-150838](https://issues.liferay.com/browse/LPS-150838). I believe a separate ticket can be opened for it since it is not related to the fix in this PR.

Can we proceed with merging this fix?

**Comment by moltam89** [comment]
Hi @noornajj ,

I think we should try and fix the issue completely.

Best,
Tamas

**Comment by moltam89** [comment]
We had a meeting with @noornajj , and we agreed to move forward with this fix. It solves the issue when we select the Global scope.
Solving this for page scopes is tricky, I opened LPS-166880 to track the problem.

 I rebased and sent it for QA here: https://github.com/liferay-staging/liferay-portal/pull/168.
 
 Thanks Noor for pushing this and sorry for blocking it for a while.

**Pull request closed without merging**
