### PR TITLE
LPS-190360 - As a Site Administrator I would like to see Staging recommendation before publishing

### PR DESCRIPTION
**Pull request by DaniSzimko**
From https://github.com/liferay-staging/liferay-portal/pull/438

cc @JessieZhao0714

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Review by JessieZhao0714 — APPROVED** [review]

**Review by JessieZhao0714 — APPROVED** [review]

**Review by JessieZhao0714 — COMMENTED** [review]
Need to update recommendation content in test cases.

**Comment by JessieZhao0714** [comment]
Update test cases and continue in #446

**Comment by JessieZhao0714** [comment]
Update test cases and continue in #446 

cc @DaniSzimko and @gaborlovasdotcom

**Pull request closed without merging**
