### PR TITLE
LPS-187977 Remove VIEW permissions to Guest users. This will stop including Staging Bar portlet javascript headers when the user is Guest

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-187977

Guest users never have access to the StagingBarPortlet but its javascript headers are always included to the page.
This increases page size, penalizing SEO score.

To avoid the issue I am removing the VIEW permission to the Guest users, this will prevent the frontend infraestructure from adding the javascript header when generating the page headers.
After analyzing current logic where the javascript headers are added, I don't think there is other alternative without manually hardcoding some Staging logic on the Frontend side.

#### Frontend logic that adds the javascript headers
For more information about this frontend logic, see:
 - https://github.com/liferay/liferay-portal/blob/bc45ce41d977adbdffd7e2fdd5ea15e82fb58acb/portal-web/docroot/html/common/themes/top_head.jsp#L34
 - https://github.com/liferay/liferay-portal/blob/bc45ce41d977adbdffd7e2fdd5ea15e82fb58acb/portal-web/docroot/html/common/themes/top_portlet_resources_js.jspf#L20
 - https://github.com/liferay/liferay-portal/blob/bc45ce41d977adbdffd7e2fdd5ea15e82fb58acb/portal-kernel/src/com/liferay/portal/kernel/portlet/render/PortletRenderUtil.java#L147
 
#### Default permissions of a portlet
If a portlet doesn't have any defined `portlet.properties` and `resource-actions/default.xml` files, the default effective permissions are defined here https://github.com/liferay/liferay-portal/blob/bc45ce41d977adbdffd7e2fdd5ea15e82fb58acb/portal-impl/src/com/liferay/portal/security/permission/ResourceActionsImpl.java#L752-L792, so they are:

- **Owner:** ACCESS_IN_CONTROL_PANEL, ADD_TO_PAGE, CONFIGURATION, PERMISSIONS, PREFERENCES, VIEW
- **Group:** VIEW 
- **Guest:** VIEW

After my code changes, I am setting the default permissions of StagingBarPortlet:
- **Owner:** VIEW
- **Group:** VIEW 
- **Guest:** None
- **Guest unsupported:** VIEW

Let me know if you need more information

### CODE REVIEW

**Comment by JessieZhao0714** [comment]
ci:test:staging

**Comment by JessieZhao0714** [comment]
A unique failure was found.
Affect testcase: [LocalFile.StagingUsecase#TrashEntryReferencePublishing](https://testray.liferay.com/home/-/testray/case_results/2353759712?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2353759053%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
cc @jorgediaz-lr, @vendeltoreki and @JoyceWang08211 

Steps to reproduce:
1. Import the SQL file from https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-staging-with-deleted-user-mysql.zip into the database
2. Upgrade to master
3. Navigate to the staged site
4. Make a publication

Expected result: The publication is successful without errors.
Actual result: The publication fails with the below error
`2023-06-20 03:12:55.712 ERROR [liferay/background_task-4][LoggerExportImportLifecycleListener:399] Staged model {class: com.liferay.portal.kernel.model.Layout, groupId: 10474, uuid: 52405a07-11f0-392f-85d4-ee7f16556cba} import failed
com.liferay.portal.kernel.security.auth.PrincipalException: VIEWis not supported by role 10163
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._updateResourcePermission(ResourcePermissionLocalServiceImpl.java:2215) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.updateResourcePermission(ResourcePermissionLocalServiceImpl.java:1913) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.setResourcePermissions(ResourcePermissionLocalServiceImpl.java:1606) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1079.setResourcePermissions(Unknown Source) ~[?:?]
	at com.liferay.portal.kernel.service.ResourcePermissionLocalServiceWrapper.setResourcePermissions(ResourcePermissionLocalServiceWrapper.java:1083) ~[portal-kernel.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1080.setResourcePermissions(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:99) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy79.setResourcePermissions(Unknown Source) ~[?:?]
	at com.liferay.portal.kernel.service.ResourcePermissionLocalServiceUtil.setResourcePermissions(ResourcePermissionLocalServiceUtil.java:1000) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.internal.util.ExportImportPermissionUtil.updateResourcePermissions(ExportImportPermissionUtil.java:165) ~[?:?]
	at com.liferay.exportimport.internal.lar.PermissionImporterImpl._importPermissions(PermissionImporterImpl.java:288) ~[?:?]
	at com.liferay.exportimport.internal.lar.PermissionImporterImpl.importPortletPermissions(PermissionImporterImpl.java:106) ~[?:?]
	at com.liferay.layout.admin.web.internal.exportimport.data.handler.LayoutStagedModelDataHandler._importLayoutPortlets(LayoutStagedModelDataHandler.java:2323) ~[?:?]
	at com.liferay.layout.admin.web.internal.exportimport.data.handler.LayoutStagedModelDataHandler.doImportStagedModel(LayoutStagedModelDataHandler.java:955) ~[?:?]
	at com.liferay.layout.admin.web.internal.exportimport.data.handler.LayoutStagedModelDataHandler.doImportStagedModel(LayoutStagedModelDataHandler.java:166) ~[?:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:367) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:389) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:375) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.doImportReferenceStagedModel(StagedModelDataHandlerUtil.java:462) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importReferenceStagedModel(StagedModelDataHandlerUtil.java:304) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importReferenceStagedModels(BaseStagedModelDataHandler.java:863) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:365) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:389) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:375) ~[portal-kernel.jar:?]
	at com.liferay.site.internal.exportimport.data.handler.StagedGroupStagedModelDataHandler.doImportStagedModel(StagedGroupStagedModelDataHandler.java:291) ~[?:?]
	at com.liferay.site.internal.exportimport.data.handler.StagedGroupStagedModelDataHandler.doImportStagedModel(StagedGroupStagedModelDataHandler.java:74) ~[?:?]
	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:367) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:389) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:375) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.internal.controller.LayoutImportController._importFile(LayoutImportController.java:933) ~[?:?]
	at com.liferay.exportimport.internal.controller.LayoutImportController.importFile(LayoutImportController.java:218) ~[?:?]
	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.importLayouts(ExportImportLocalServiceImpl.java:194) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy137.importLayouts(Unknown Source) ~[?:?]
	at com.liferay.exportimport.internal.background.task.LayoutStagingBackgroundTaskExecutor$LayoutStagingImportCallable.call(LayoutStagingBackgroundTaskExecutor.java:305) ~[?:?]
	at com.liferay.exportimport.internal.background.task.LayoutStagingBackgroundTaskExecutor$LayoutStagingImportCallable.call(LayoutStagingBackgroundTaskExecutor.java:278) ~[?:?]
	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:36) [portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39) [portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28) [portal-kernel.jar:?]
	at com.liferay.exportimport.internal.background.task.LayoutStagingBackgroundTaskExecutor.execute(LayoutStagingBackgroundTaskExecutor.java:141) [bundleFile:?]
	at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:63) [bundleFile:?]
	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:41) [portal-kernel.jar:?]
	at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:72) [bundleFile:?]
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:124) [bundleFile:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
`

**Comment by jorgediaz-lr** [comment]
Hi @JessieZhao0714 

I cannot download the https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-staging-with-deleted-user-mysql.zip file

How can I obtain it?

Thank you

**Comment by jorgediaz-lr** [comment]
@achaparro sent the ZIP to me, I am going to test it locally.

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1267401_10030

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
Hi @jorgediaz-lr, the upgrade issue has been resolved and no regression issues were found.
Thanks for your quick fix!
cc @vendeltoreki and @gaborlovasdotcom

**Comment by DaniSzimko** [comment]
ci:forward

**Pull request closed without merging**
