### PR TITLE
LPS-185442 - deprecate Relationship modules

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-185442](https://issues.liferay.com/browse/LPS-185442) - Deprecate Relationship modules
Information on how to deprecate entire modules : [App.bnd](https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/1650623654/App.bndl) , [How to Deprecate Features](https://liferay.atlassian.net/wiki/spaces/PDMG/pages/1409777713/How+to+Deprecate+Features) , [Slack help from supportability team](https://liferay.slack.com/archives/CL69QNT61/p1686305768638099)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Review by vendeltoreki — APPROVED** [review]
These changes look good to me, I think we can forward them.

**Comment by laszlopap** [comment]
ci:forward

**Pull request closed without merging**
