### PR TITLE
[TS] LPP-48345 > LPS-180569 Allow paths defined in virtual.hosts.ignore.paths to be validated

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi team,
This PR is for fixing the [LPS-180569 ](https://issues.liferay.com/browse/LPS-180569)
You could see the answers for this behavior https://issues.liferay.com/browse/PTR-3800
The ori [PR](https://github.com/ces-quanhuynh/liferay-portal/pull/23) is passed my review. 
Please review and leave you comment.
Thanks,
Quan

### CODE REVIEW

**Comment by tototrinh** [comment]
Hi @vendeltoreki,
Thanks for your review.
Since this fix is crucially needed with the issue impacting the client’s content creation process. The client requests a fix if this PR is approved without merging into the Master (SDH format delivery). So could you please help confirm that the fix is safe to provide to the customer now or should I wait for the test failures to check?
Thanks.

**Comment by JoyceWang08211** [comment]
> ###  ci:test:staging - 190 out of 198 jobs passed in 1 hour 27 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4430) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1377401_10333
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [951c0e6f3c24c9cc58c631fad10fc21653385191](https://github.com/liferay/liferay-portal/commit/951c0e6f3c24c9cc58c631fad10fc21653385191)
> 
> #### Upstream Comparison:
> Branch GIT ID: [405196303c0776bec8408529e80ea5f6aa2a1490](https://github.com/liferay/liferay-portal/commit/405196303c0776bec8408529e80ea5f6aa2a1490)Jenkins Build URL: [EE Development Acceptance (master) - 4429 - 2023-04-02[16:48:28]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2255490582)
> 
> **ci:test:staging - 190 out of 198 jobs PASSED**
> ##### For more details click [here](https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10333/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/4/10](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/517152//consoleText)print-jstack-logs:
>         [echo] Executing commands: 
>         [echo] 
>         [echo] jps > jps_output
>         [echo] 
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
>    [stopwatch] [test.execution.duration: 29:24.052 sec]
>    [stopwatch] [run.batch.test.action: 29:52.484 sec]
>         [echo] The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1647: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1651: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:39: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:51: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:15324: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:15667: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:6780: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:6857: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8032: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8211: Unable to find startup message after 30 minutes.
>          [get] Getting: \$\{dependencies.url\}/archive/test-1-38/test-portal-acceptance-pullrequest-downstream(master)/517152consoleText
>          [get] To: /opt/dev/projects/github/liferay-portal/20230402230723231.txt
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230402230723231.txt
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1781859008.properties1. [LocalFile.StagingUpgrade#DefaultSiteCanBeExportedAfterUpgrade71103](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/517152//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUpgrade_DefaultSiteCanBeExportedAfterUpgrade71103_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/4/10/LocalFile.StagingUpgrade_DefaultSiteCanBeExportedAfterUpgrade71103/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/4/10/LocalFile.StagingUpgrade_DefaultSiteCanBeExportedAfterUpgrade71103/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/4/10/jenkins-console.txt.gz)
> 2. [functional-tomcat90-mysql57-jdk8/7/1](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532412//consoleText)     [echo] https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10333/functional-tomcat90-mysql57-jdk8/7/1/jstacks/DBUpgrader__438698.log
>         [echo] 
>         [echo] ##
>         [echo] ## /tmp/jenkins/test-1-26/test-portal-acceptance-pullrequest-downstream(master)/532412/jstacks/DBUpgrader__438698.log
>         [echo] ##
>         [echo] 
>    [beanshell] 2023-04-02 22:50:30
>    [beanshell] Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode):
>    [beanshell] 
>    [beanshell] "Attach Listener" #149 daemon prio=9 os_prio=0 tid=0x00007fa1f0001000 nid=0x6b321 waiting on condition [0x0000000000000000]
>    [beanshell]    java.lang.Thread.State: RUNNABLE
>    [beanshell] 
>    [beanshell]    Locked ownable synchronizers:
>    [beanshell]   - None
>    [beanshell] 
>    [beanshell] "ForkJoinPool-18-worker-3" #143 daemon prio=5 os_prio=0 tid=0x00007fa158011800 nid=0x6b280 waiting for monitor entry [0x00007fa2133f1000]
>    [beanshell] 
>       [delete] Deleting: /tmp/DBUpgrader__438698.log
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
>    [stopwatch] [test.execution.duration: 15:35.967 sec]
>    [stopwatch] [run.batch.test.action: 16:02.721 sec]
>         [echo] The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:365: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1647: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1651: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:39: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:51: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:14907: The following error occurred while executing this line:
>         [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:16417: Timeout: killed the sub-process
>          [get] Getting: \$\{dependencies.url\}/archive/test-1-26/test-portal-acceptance-pullrequest-downstream(master)/532412consoleText
>          [get] To: /opt/dev/projects/github/liferay-portal/20230402225030420.txt
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230402225030420.txt
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/null893650848.properties1. [LocalFile.WebContentStagingUpgrade#PublishStagingArchiveAfterUpgrade625](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/532412//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WebContentStagingUpgrade_PublishStagingArchiveAfterUpgrade625_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/7/1/LocalFile.WebContentStagingUpgrade_PublishStagingArchiveAfterUpgrade625/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/7/1/LocalFile.WebContentStagingUpgrade_PublishStagingArchiveAfterUpgrade625/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/7/1/jenkins-console.txt.gz)
> 3. [functional-tomcat90-mysql57-jdk8/1/13](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/461638//consoleText)1. [LocalFile.PGStaging#AddDMDocumentWCArticleStagingLocalLive](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/461638//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGStaging_AddDMDocumentWCArticleStagingLocalLive_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/1/13/LocalFile.PGStaging_AddDMDocumentWCArticleStagingLocalLive/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/1/13/LocalFile.PGStaging_AddDMDocumentWCArticleStagingLocalLive/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/1/13/jenkins-console.txt.gz)
> 4. [functional-tomcat90-mysql57-jdk8/2/9](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52156//consoleText)1. [PoshiRunner.initializationError](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52156//testReport/com.liferay.poshi.runner/PoshiRunner/initializationError) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/PoshiRunner.initializationError/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/PoshiRunner.initializationError/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/jenkins-console.txt.gz)2. [LocalFile.ExportImport#ExportImportLayoutCircularReference](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52156//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ExportImport_ExportImportLayoutCircularReference_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/LocalFile.ExportImport_ExportImportLayoutCircularReference/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/LocalFile.ExportImport_ExportImportLayoutCircularReference/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/2/9/jenkins-console.txt.gz)
> 5. [functional-tomcat90-mysql57-jdk8/5/16](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429935//consoleText)1. [LocalFile.StagingUpgrade#ViewStagingDefaultSettingAfterUpgrade721](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429935//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_StagingUpgrade_ViewStagingDefaultSettingAfterUpgrade721_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/5/16/LocalFile.StagingUpgrade_ViewStagingDefaultSettingAfterUpgrade721/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/5/16/LocalFile.StagingUpgrade_ViewStagingDefaultSettingAfterUpgrade721/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10333/functional-tomcat90-mysql57-jdk8/5/16/jenkins-console.txt.gz)
> 6. ...

No unique failures were found.
cc @vendeltoreki

**Comment by vendeltoreki** [comment]
Hi @tototrinh ,

I think it's safe to forward this PR and create a hotfix from it.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
