### PR TITLE
LPS-161240 Add publish date when publish staging layout to live or remote

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is the PR for the ticket https://issues.liferay.com/browse/LPS-161240.
The issue is caused by the line https://github.com/liferay/liferay-portal/blob/326c4b561939843d20dbf5c06f1c8091eb8ded87/modules/dxp/apps/analytics/analytics-reports-web/src/main/java/com/liferay/analytics/reports/web/internal/portlet/action/GetDataMVCResourceCommand.java#L352. But the root cause is the lack of the publishDate information. So in this PR, the author implemented the publishDate update.
Could you please help me to review this PR and leave your comments?
Thank you.
CC: @binhtran92

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by binhtran92** [comment]
ci:test:relevant

**Comment by binhtran92** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
@vendeltoreki relevant tests are not connected to the contents of the PR.

**Comment by moltam89** [comment]
Hi guys,

Is this issue really page versioning specific, couldn't we reproduce this without versioning, or a simple site LAR export/import, maybe with Site Templates?

**Note:**
Changes in LayoutStagedModelDataHandler are usually reviewed by the Echo Team.

Best,
Tamas

**Comment by JoyceWang08211** [comment]
BTW, I also encountered the NPE issue when testing on site template. Please see the details [here](https://issues.liferay.com/browse/LPS-161240?focusedCommentId=2764108&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2764108).

cc @moltam89

**Comment by binhtran92** [comment]
Hi all, since this issue is caused by the analytics report should we return the `modifiedDate` in case the `publishDate` is not set? [getPublishDate](https://github.com/liferay/liferay-portal-ee/blob/master/modules/dxp/apps/analytics/analytics-reports-layout-impl/src/main/java/com/liferay/analytics/reports/layout/internal/info/item/LayoutAnalyticsReportsInfoItem.java#L133,L135)
I'm not sure that the publishDate will be set for all layouts.

**Comment by moltam89** [comment]
Hi @binhtran92 ,

I'm not sure who should answer your question, the Staging Team doesn't handle application specific logic.

As Joyce confirmed that the issue is reproducible with Site Templates as well, I assume that this cannot be the final solution, so I'm closing this PR.

Best,
Tamas

**Pull request closed without merging**
