### PR TITLE
LPS-122862 | master

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-122862

Updated https://github.com/liferay-staging/liferay-portal/pull/12

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Hi @holatuwol ,

Thanks for submitting these changes.
As I see, the case `LocalFile.CPSitetemplates#ViewJavaScriptPropagateviaSiteTemplate` is still failing. You can check its reproduction steps in [LRQA-68015](https://issues.liferay.com/browse/LRQA-68015). I've tested it locally without this change, and it worked correctly before.

The other failing staging test cases (`LocalFile.RemoteStaging#StagingRemoteLiveWebContentViaPortletPG`, `LocalFile.RemoteStaging#PublishCustomFieldDeletionviaRemoteStaging`) don't seem to be relevant.

**Comment by holatuwol** [comment]
ci:test:staging

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
It seems like these tests failed mostly because of CI infrastructure issues:
* LocalFile.StagingActivation#CheckPublicationSummaryRemote
* LocalFile.Staging#EditWikiPageInLiveSiteWhenWikiNotStaged
* LocalFile.Staging#PublishChildSiteViaRemoteStagingWithParentStructure
* LocalFile.Staging#PublishVocabularyDeletionViaRemoteStagingOnGlobalSite
* LocalFile.StagingUsecase#ActivateStagingForSiteWithTheme
* LocalFile.StagingUsecase#PublishThemeFromStagedToLive

@gaborlovasdotcom , can you please verify?

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
