### PR TITLE
[TS] LPS-157852 GroupLocalServiceUtil.validateRemote is not correctly validating that the remote group belongs to the same company than the user

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-157852

The method `GroupLocalServiceUtil.validateRemote` is used from staging logic.

This regression was caused by [LPS-89294](https://issues.liferay.com/browse/LPS-89294), this commit https://github.com/brianchandotcom/liferay-portal/pull/83605/commits/8c2efa6b5ddeb718207f2ff1e382886d3acea8c6#diff-809c64f8ed9e550f63935bdd9fc3d34e1780651d80004c804c6a7ea4806c185bR5118 started to use GroupService.class to call the remote server, but this is not accepted by TunnelServlet, see https://github.com/liferay/liferay-portal/blob/d7eaa1436b2006f79901d43bced1579d3089dd03/portal-impl/src/com/liferay/portal/servlet/TunnelServlet.java#L161-L172 so the call is silently ignored and no validations are executed in the remote server.

If you apply [LPS-157845](https://issues.liferay.com/browse/LPS-157845) correction and you activate the warn log level of com.liferay.portal.servlet.TunnelServlet you will also see a warn exception saying "Invalid request interface com.liferay.portal.kernel.service.GroupService"

The correction is very simple, just replacing `GroupService.class` with `GroupServiceUtil.class` in the TunnelUtil.invoke call, see commit https://github.com/liferay-staging/liferay-portal/commit/bf793d9623c0d786d7925cce8b3023bf8e900e46

The problem here is the JavaServiceUtilCheck SF rule doesn't allow importing any *ServiceUtil class, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/java_service_util_check.markdown

To solve this issue the only idea is to avoid importing the class and load it using `Class.forName`, see https://github.com/liferay-staging/liferay-portal/commit/62dd83f4f3ceeecae467362c0e38d254a485500d it is a bit ugly but I don't have any other idea.

Let me know if I should change anything.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1327401_4668

**Comment by JoyceWang08211** [comment]
All the above functional failures are not related to the current changes. I've validated on local env. 
cc @gaborlovasdotcom

**Comment by vendeltoreki** [comment]
I've tested and debugged the changes in a remote staging environment and the methods seem to be invoked correctly

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
