### PR TITLE
LPS-190360 - As a Site Administrator I would like to see Staging recommendation before publishing

### PR DESCRIPTION
**Pull request by JessieZhao0714**
From #445 

cc @DaniSzimko

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by laszlopap** [comment]
ci:forward

**Pull request closed without merging**
