### PR TITLE
LPS-157427

### PR DESCRIPTION
**Pull request by mbowerman**
I only applied this fix to `portlet_list/page.jsp` because that is used when doing a Site-scoped publish process, which always gets the dateRange used in the actual publish by calling `ExportImportDateUtil.getDateRange` with a null portletId.

I did not apply it to `publish_portlet_publish_or_copy.jsp` (Portlet-scoped publish process) because that publish process actually does use the portletId of the portlet when getting the date range, so we should keep that .jsp using the portletId of the portlet when rendering the changes in the UI to be consistent with what the publish does.

https://issues.liferay.com/browse/LPS-157427

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @mbowerman ,

Sorry for the delay in the review. I looked into the changes, but I think that's not the best solution here. I think the main problem is that the UI is confusing when there's no item to publish, only deletions for that specific item. This solution only gets rid of the deletion by changing the date range.
If you click on the "Replicate Individual Deletions" checkbox, the list will show correctly, that there's 1 deletion to publish. Even though this doesn't really make sense in this scenario, since it has never been published, but it's logically correct from staging's point of view.
So this item appearing on the list only makes sense when this checkbox is checked. I will discuss with the product team how we should solve this the right way.
My initial thought is that we should somehow disable or even hide the "Web Content" item in this case, unless the "Replicate Individual Deletions" checkbox is active.

**Comment by mbowerman** [comment]
Hi @vendeltoreki ,

Good point, I had incorrectly assumed that this was an inconsistency between the way we get the deletions to be published in the UI and the way we get the deletions to be published during the actual staging process.

I ran a quick test and saw that when publishing the deletions during the staging process, we use the "last-publish-date" of the PortletPreferences to publish them, rather than using the "Last Publish Date" of the most recent Staging Process. Which is the same as we did when getting the deletions for the UI, before this fix.

It is strange to me though that we take a different approach as to what "Last Publish Date" means when publishing deletions vs. publishing creations of assets.

I'll go ahead and work on implementing the fix you described, to hide the portlet in this scenario unless "Replicate Individual Deletions" is selected. However, I do have one concern which is that it may not be obvious to the user that they need to click the "Refresh Counts" button after selecting the "Replicate Individual Deletions" checkbox, since the "Refresh Counts" button and "Replicate Individual Deletions" button are on different sections of the page.

**Comment by mbowerman** [comment]
Hi @vendeltoreki,

Please ignore my concern mentioned in the last paragraph. I found an elegant way to make it update automatically on clicking the "Replicate Individual Deletions" checkbox with no need to click the "Refresh Counts" button. I'll send my fix in for review shortly.

**Pull request closed without merging**
