### PR TITLE
LPS 176405 fix

### PR DESCRIPTION
**Pull request by ealonso**
- LPS-176405 live groups web contents will appear in the item selector, if staging is not set for web contents
- LPS-176405 Adds new method to get the group taking into account if the portlet is staged or not
- LPS-176405 Reuse logic
- LPS-176405 Also apply to info item selectors
- LPS-176405 build.gradle
- LPS-176405 Use the local service calls + prepare for remote staging as well

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Fix semantic versioning failure and send to Brian since failures are unrelated see: https://github.com/brianchandotcom/liferay-portal/pull/131545

**Pull request closed without merging**
