### PR TITLE
LPS-190064, LPS-194891 | master

### PR DESCRIPTION
**Pull request by GergoMathe**
[LPS-190064](https://liferay.atlassian.net/browse/LPS-190064)
[LPS-194891](https://liferay.atlassian.net/browse/LPS-194891)

### CODE REVIEW

**Comment by GergoMathe** [comment]
ci:test:staging:nocompile

**Comment by GergoMathe** [comment]
ci:test:staging:nocompile

**Comment by GergoMathe** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:stop

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
See my [comments](https://liferay.atlassian.net/browse/LPS-190064?focusedCommentId=2478928) on the connecting ticket

**Pull request closed without merging**
