### PR TITLE
LPS-176405 

### PR DESCRIPTION
**Pull request by vendeltoreki**
Forwarding: https://github.com/liferay-staging/liferay-portal/pull/251

Added commit: https://github.com/liferay-staging/liferay-portal/commit/801793df9e43127d4b601c194aa4257fed9694b8

cc: @ealonso , @GaborKomaromi

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:stop

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @vendeltoreki,

I've fix the rebase error and resend here: https://github.com/liferay-staging/liferay-portal/pull/258

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
