### PR TITLE
[TS] LPS-190044 Ensure friendly URL entries are deleted on the live site when publishing

### PR DESCRIPTION
**Pull request by jonathanmccann**
This logic mirrors closely the existing method "_deleteMissingLayoutFriendlyURLs". I wanted to get the approval from the Staging team prior to sending it along to the Echo team for review.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by JessieZhao0714** [comment]
Hi @DaniSzimko, no regression issues were found.

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:forward:force

**Comment by DaniSzimko** [comment]
Hi @jonathanmccann ,
These changes look good to me from the staging side.
I forwarded this PR to Brian by mistake, but I closed the request.

**Comment by jonathanmccann** [comment]
@DaniSzimko Thank you for reviewing this. I've forwarded it along here - https://github.com/liferay-echo/liferay-portal/pull/12855

**Pull request closed without merging**
