### PR TITLE
LRQA-77952 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-77952

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:echo:nocompile

**Comment by JoyceWang08211** [comment]
LGTM, wait for Jenkins results of ci:test:echo

**Comment by epark18** [comment]
ci:test:echo:nocompile

**Comment by epark18** [comment]
@JoyceWang08211 The test passed with new changes. [WebContentExportImport#ContentWillDisplayInOrderInRepeatableWCFields.](https://testray.liferay.com/home/-/testray/case_results/2028654028)

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
