### PR TITLE
LRQA-76628

### PR DESCRIPTION
**Pull request by weller0246**
https://issues.liferay.com/browse/LRQA-76628

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:help

**Comment by weller0246** [comment]
ci:test:lima:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:lima:nocompile

**Review by gaborlovasdotcom — APPROVED** [review]

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Pull request closed without merging**
