### PR TITLE
LPS-200974

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this?

https://liferay.atlassian.net/browse/LPS-200974
Best,
Attila

------

The modified code only affects this behavior based on my searches the isDataPortletInstanceLevel in the PortletDataHandlers is only used at one specific point in the export/import. The root cause of the issue is that the data changes related to deletion events are only exported from XX hours when the selected portlet is not an instanceLevel portlet.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by GezaGroma** [comment]
Hi Team,
Could someone please push this PR forward, and could we provide this solution to our customers as soon as possible? They have been waiting for it for quite a while.

Thanks a lot.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
