### PR TITLE
[TS] LPS-144604

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-144604

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @ChrisKian ,

It seems like a recently merged pull request is using a different approach in terms of page selection: https://github.com/liferay-staging/liferay-portal/pull/26 . 
However, the case of [LPS-144446](https://issues.liferay.com/browse/LPS-144446) makes sense, it kind-of contradicts how staging handled page selections previously.
We will discuss this with the Staging Product Team, to find out what would be the right behavior.
At the moment, the [LPS-144604](https://issues.liferay.com/browse/LPS-144604) case with these changes is failing on the current master, because of https://github.com/liferay/liferay-portal/commit/10b0c5a7ce0f1b765176df6a673bc5afd004e4b5 commit.

**Comment by ChrisKian** [comment]
Thanks @vendeltoreki,
I believe the approach I am taking with this PR makes more sense and allows for more flexibility.

With LPS-144446, there is no way to define all Public/Private pages currently AND in the future if more are created.  The only way to accommodate for new pages is to edit the Publish Template.  The reproduction steps also don't make sense, since the user has selected "Public Pages" but doesn't want all public pages?

With LPS-144604, we can accommodate for new pages as well as keep a limited sub-set if needed.

Please let me know if there is anything I can help with, thanks!

**Comment by vendeltoreki** [comment]
Hi @ChrisKian ,

We discussed this with the staging product team. I'm forwarding your changes on https://github.com/liferay-staging/liferay-portal/pull/29 , which also reverts https://github.com/liferay-staging/liferay-portal/commit/10b0c5a7ce0f1b765176df6a673bc5afd004e4b5 . [LPS-144446](https://issues.liferay.com/browse/LPS-144446) will most likely be fixed another way in the future, by modifying the behavior of the page tree front-end component.

**Pull request closed without merging**
