### PR TITLE
LPS-190736, LPS-196892 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-190736
https://liferay.atlassian.net/browse/LPS-196892

cc @DaniSzimko

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
For the stable run, no consistent failure was found. I will send PR to BChan directly.

**Comment by laszlopap** [comment]
Thanks  @JoyceWang08211 ! Could you please link the new PR to https://liferay.atlassian.net/browse/LPS-190736 ?

**Comment by JoyceWang08211** [comment]
> Thanks @JoyceWang08211 ! Could you please link the new PR to https://liferay.atlassian.net/browse/LPS-190736 ?

I sent it to BChan and I updated the ticket.

**Pull request closed without merging**
