### PR TITLE
LPS-162566 Add CSS

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-169001](https://issues.liferay.com/browse/LPS-169001) issue fixed the "Pages to Publish" part with a new scss file and import, so I added new css to the existing scss file to fix the "Date range" part.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by DaniSzimko** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
