### PR TITLE
[TS] LPS-163773 NoSuchResourcePermissionException when re-adding the site template with the same name

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-163773](https://issues.liferay.com/browse/LPS-163773), the original has passed my review at sontruongces#42. Please help me to review and give feedback.

Thanks
cc: @TaiPhamLR

### CODE REVIEW

**Comment by moltam89** [comment]
Hi guys,

The fix looks good to me, I'm forwarding it to Brian.

Thanks,
Tamas

**Comment by moltam89** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Comment by gaborlovasdotcom** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/124116

**Pull request closed without merging**
