### PR TITLE
[TS] LPS-185987 | Adding missing integration tests

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this?

https://liferay.atlassian.net/browse/LPS-185987
Best,
Attila

This is a follow-up pull request based on: https://github.com/brianchandotcom/liferay-portal/pull/140151

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by GergoMathe** [comment]
Hi @DaniSzimko! The only relevant issue is:
`beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.exportimport.kernel.lar                MINOR      5.1.0      5.1.0      5.2.0      VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.exportimport.kernel.lar.ExportImportHelperUtil
[beanshell] 		+   method     getDataSiteAndInstanceLevelPortlets(long)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.util.List
[beanshell] 		+   method     getDataSiteAndInstanceLevelPortlets(long,boolean)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.util.List
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 123.1.0`

**Comment by DaniSzimko** [comment]
Hi @bakayattila ,
The code looks OK, could you fix the semantic versioning please?

Thank you,
Daniel

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi @DaniSzimko,
Fixed the server version and the merge conflict.
Best,
Attila

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
@bakayattila could you fix the PMD violation please?

**Comment by bakayattila** [comment]
Hi @DaniSzimko,
I fixed the PMD violation.
Best,
Attila

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
ci:test:stable

**Comment by JessieZhao0714** [comment]
No regression was found, PortalSmokeUpgrade#ViewPortalSmokeArchive7310 failed during the stable run due to [LPS-122481](https://liferay.atlassian.net/browse/LPS-122481).
cc @DaniSzimko and @bakayattila

**Comment by DaniSzimko** [comment]
ci:forward:force

**Pull request closed without merging**
