### PR TITLE
LRQA-79387 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-79387

cc./ @gaborlovasdotcom

### CODE REVIEW

**Review by gaborlovasdotcom — COMMENTED** [review]
@melodywu Could you please run the local source format, and force push the changes?

**Comment by melodywu** [comment]
> @melodywu Could you please run the local source format, and force push the changes?

Sorry for the sf issue.

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:forward

**Review by gaborlovasdotcom — APPROVED** [review]

**Pull request closed without merging**
