### PR TITLE
[TS] LPS-150602 Cancel site template propagation import background task when other tasks are scheduled for the same site

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPS-150602](https://issues.liferay.com/browse/LPS-150602)

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
This looks great, I think we should enable this feature by default.

**Comment by moltam89** [comment]
The next step is QA, cc @gaborlovasdotcom , @weller0246.

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by weller0246** [comment]
ci:test:bundle

**Comment by vendeltoreki** [comment]
Force pushed commits to avoid conflict in `modules/apps/export-import/export-import-service/build.gradle`

**Comment by JessieZhao0714** [comment]
ci:test:bundle

**Comment by vendeltoreki** [comment]
Forwarding, since the test automation of [LPS-150602](https://issues.liferay.com/browse/LPS-150602) has been separated to [LPS-164494](https://issues.liferay.com/browse/LPS-164494) ticket.

cc: @gaborlovasdotcom

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
