### PR TITLE
LPS-182567 add ConfirmModal to the New Import Process Layout if Delet…

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-182567](https://issues.liferay.com/browse/LPS-182567) Added ConfirmModal to the New Import Process Layout if Delete Application Data Before Importing is checked

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
No regression was found in ci:test:staging run.

**Comment by laszlopap** [comment]
ci:test:bundle

**Comment by laszlopap** [comment]
ci:forward

**Pull request closed without merging**
