### PR TITLE
LPS-143860

### PR DESCRIPTION
**Pull request by cleydyr**
Related to https://issues.liferay.com/browse/LPS-143860

The main part of the fix only works when staging.use.hibernate.commit.flush.mode=true in portal-ext.properties.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
I'm checking the rebased version of this branch on https://github.com/vendeltoreki/liferay-portal/pull/238 .
It seems like the
* `LocalFile.ExportImport#ExportImportLayoutCircularReference`
* `LocalFile.ExportImport#ExportImportSmoke`

tests are consistently failing. I'm checking their use-cases manually. E.g.: [LPS-133752](https://issues.liferay.com/browse/LPS-133752)

**Comment by vendeltoreki** [comment]
Forwarding to: https://github.com/liferay-core-infra/liferay-portal/pull/137

**Pull request closed without merging**
