### PR TITLE
LPS-166513 As a Site Admistrator, I want the exported Site and Portlet LAR files to be removed from the Document and Media library

### PR DESCRIPTION
**Pull request by hhtank**

### CODE REVIEW

**Comment by hhtank** [comment]
To reviewers: This PR also included **_LPS-166514 As a Site Admistrator, I want the Sites and Portlet LAR files used for imports to be removed from the Document and Media library_**

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by hhtank** [comment]
ci:test:bundle

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:sf
ci:test:staging

**Comment by hhtank** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
