### PR TITLE
LPS-195766 - XSS with `searchContainerId` in Asset Libraries import

### PR DESCRIPTION
**Pull request by DaniSzimko**
https://liferay.atlassian.net/browse/LPS-195766

use HtmlUtil.escapeJS to encode possible scripts in the url as params in Asset Libraries export/import

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Review by vendeltoreki — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
