### PR TITLE
LRQA-77968 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-77968

cc @JoyceWang08211 @gaborlovasdotcom

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by gaborlovasdotcom** [comment]
Forwarded directly in https://github.com/brianchandotcom/liferay-portal/pull/125442

**Pull request closed without merging**
