### PR TITLE
[Story] LPS-190628 - As a Site Administrator I would like to be able to transfer Client Extension related portlets during staging process

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-190628](https://liferay.atlassian.net/browse/LPS-190628)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Resolved the conflict and rebase to the latest master to include the fix of stable issue.
Continued here: https://github.com/liferay-staging/liferay-portal/pull/391

**Pull request closed without merging**
