### PR TITLE
LPS-151989 Prevent null pointer exception

### PR DESCRIPTION
**Pull request by ealonso**
Hey guys,

I'm fixing the issue preventing the null pointer exception, but I don't understand at all why this method is executed when we are doing an upgrade process, so I'm sending it to you to validate if it is the correct fix or if the root cause of it is another one.

Please let me know if you need more information.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
The NPE error is fixed at the current PR, see details:
Testray Link: [StagingUpgrade#TemplatePropagationShouldWorkAfterUpgrade73101](https://testray.liferay.com/home/-/testray/case_results/1694175591)
Console log: https://testray.liferay.com/reports/production/logs/2022-04/test-1-38/test-portal-acceptance-pullrequest(master)/88/functional-tomcat90-mysql57-jdk8/4/2/jenkins-console.txt.gz?authuser=0

But the AP widget doesn't display in home page after upgraded from 7.3.10.1 to master. See [poshi report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-38/test-portal-acceptance-pullrequest(master)/88/functional-tomcat90-mysql57-jdk8/4/2/LocalFile.StagingUpgrade_TemplatePropagationShouldWorkAfterUpgrade73101/index.html.gz?authuser=0).

**Steps to reproduce:**
# Start up 7.3.10.1 release bundle.
# Add a site template named as Site Template Name.
# Add a new site based on Site Template Name named as Site Name
# Navigate to the site template page.
# Add an AP widget to home page
# Stop portal and upgrade to master
# Start up portal 
# Navigate to site page
# Refresh page

Actual result: AP widget doesn't display in home page.
Expected result: AP widget should display in home page.  

cc @ealonso and @moltam89

**Comment by gaborlovasdotcom** [comment]
cc @vendeltoreki

**Comment by moltam89** [comment]
I tend to think that we shouldn't run propagations during an upgrade process.  It might be a more general fox to prevent it.

**Comment by ealonso** [comment]
Closing this one since @moltam89 send a better fix 😍

**Pull request closed without merging**
