### PR TITLE
[TS] LPS-173582 When publishing web content folder, Link to Page fields are not be processed correctly

### PR DESCRIPTION
**Pull request by jvelalr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:reevaluate:1287401_5627

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hi @vendeltoreki ,

We tested same change in julian's repo, and it passed the tests https://github.com/jvelalr/liferay-portal/pull/5
Could someone from QA review those tests just to be sure if this is correct or not?

Thanks in advance.

**Comment by vendeltoreki** [comment]
Hi @jvelalr , @jgarcialr ,

I was looking into the code and there seems to be a way to optimize it further: at [this point in DDMFormValuesExportImportContentProcessor.transform(..)](https://github.com/liferay/liferay-portal/blob/ff2b44ec7bc2bd154004e4389ccb4d650948eb89/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/exportimport/content/processor/DDMFormValuesExportImportContentProcessor.java#L667) we already know that if `jsonObject.length() == 0` then we will not need to process anything. No need to execute `fetchImportedLayout(..)` or iterate through the missing references, since we won't find anything.
However, I might be missing something. Do you think this optimization can be valid?

Thanks,
Vendel

**Comment by jgarcialr** [comment]
Hi @vendeltoreki ,

We are testing this optimization. We think we can move it after getting valueString and before creating the jsonObject. Because if valueString is blank, none of the latter processing is needed. 

We will tell you after our tests, and force push the changes if needed.

**Comment by jvelalr** [comment]
ci:test:relevant

**Comment by jvelalr** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
1. Checked the latest ci:test:staging run on this PR against our daily test runs. Test failures are the same, except for StagingRemoteWithDynamicExportLimit, which just received a new Fix in [LRQA-78887](https://issues.liferay.com/browse/LRQA-78887). No new regression.
2. Checking [ci:test:relevant](https://github.com/liferay-staging/liferay-portal/pull/220#issuecomment-1407037577) results in [Testray](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2177304673).
Portal#Smoke fails on 2 times on MariaDB + Wildfly setup, doesn't seems related.
The only failing integration test DocumentLibraryUserNotificationTest, seems flaky, and fails due to improper DB status, aka, leftover data from previous integration tests.

So far, so good.

cc @vendeltoreki , @jvelalr

**Comment by vendeltoreki** [comment]
Thanks, @jvelalr , @gaborlovasdotcom . I'm forwarding to: https://github.com/liferay-echo/liferay-portal/pull/10962

**Pull request closed without merging**
