### PR TITLE
[TS] LPS-150838 Only import preferences to the current group

### PR DESCRIPTION
**Pull request by jonathanmccann**
If this file doesn't belong to the Staging team please let me know a better team to send it to for review.

From @noornajj:

> https://issues.liferay.com/browse/LPS-150838
> 
> The issue here is that the Global portlet permissions were being overwritten when importing site preferences and a widget was scoped to the Global site. It was occurring due to the global site being passed [here](https://github.com/liferay/liferay-portal-ee/blob/b61b73224e3dbf621004761d7480b9a1184dd02d/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextImpl.java#L1488) as the new resource and being overwritten by the imported site's settings
> 
> To fix the issue, I added an if statement to see whether the portlet being updated belongs to the new site. To do that, I check whether the current site's groupId is the same as the portlet's scopeGroupId

### CODE REVIEW

**Comment by vendeltoreki** [comment]
@gaborlovasdotcom , can you please help me validate the test failures?

Thanks,
Vendel

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
1. The failure of ExportImport#ExportImportGlobalDDMStructureViaInstances is a flaky issue.
2. The failure of CPSitetemplates#SwitchPropagationWithOneClickControl is introduced by LPS-150460.
3. The failure of StagingUsecase#PublishThemeFromStagedToLive is caused by LPS-151524.
4. The failure of com.liferay.exportimport.system.event.test.SystemEventTest.testRemoteStaging2 randomly occurs on jenkins which is reported in LPS-149657.

All the unique failures in ci:test:relevant and ci:test:staging are not related to the current PR.

**Comment by vendeltoreki** [comment]
Thanks, @JoyceWang08211 for checking the tests.

@noornajj ,

I've ran some manual tests as well with page-scoped portlets, where the `groupId` and the `scopeGroupId` is also different in the `PortletDataContext` and those also worked properly.

I think this change can move forward.

**Pull request closed without merging**
